### ISSUE TITLE
[Python 3.12] Build issue - No module named 'Cython'

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1004]
```
Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 3[53](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8896934501/job/24438570724#step:8:54), in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line [60](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8896934501/job/24438570724#step:8:61), in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8896934501/job/24438570724

**Comment by pbchekin** [comment]
A workaround for this: `pip install cython`. After explicitly installing `cython` i was able to compile triton, however there were segfaults in the core tests, see #1009.

**Comment by riverliuintel** [comment]
Please use stock PyTorch XPU source build and test to remove this dependency. BKC has sent.

**Comment by vlad-penkin** [comment]
This is an IPEX issue, #925 makes it obsolete.
