### ISSUE TITLE
[Python 3.12] `setuptools` is a required dependency for IPEX, `pkg_resources` is deprecated

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#1008]
Currently `setuptools` is not listed as a required dependency for IPEX for dev/triton-test-3.0:
https://github.com/intel/intel-extension-for-pytorch/blob/dev/triton-test-3.0/requirements.txt

Without `setuptools`, installing IPEX in a clean Python 3.12 environment and executing

```
python -c "import torch; import intel_extension_for_pytorch as ipex; print(ipex.__version__)"
```

shows the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/__init__.py", line 99, in <module>
    from . import quantization
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/quantization/__init__.py", line 1, in <module>
    from ._quantize import prepare, convert
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/quantization/_quantize.py", line 15, in <module>
    from intel_extension_for_pytorch.nn.utils._weight_prepack import (
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/nn/__init__.py", line 4, in <module>
    from .modules import FrozenBatchNorm2d
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/nn/modules/__init__.py", line 9, in <module>
    from ...cpu.nn.linear_fuse_eltwise import IPEXLinearEltwise
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/cpu/nn/linear_fuse_eltwise.py", line 3, in <module>
    from intel_extension_for_pytorch.nn.utils._weight_prepack import (
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/nn/utils/__init__.py", line 1, in <module>
    from intel_extension_for_pytorch.nn.utils import _weight_prepack
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py", line 7, in <module>
    from intel_extension_for_pytorch.cpu.tpp.utils.blocked_layout import (
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/intel_extension_for_pytorch/cpu/tpp/__init__.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

This can be solved by manually installing `setuptools`:

```
pip install setuptools
```

Note that `pkg_resources` is deprecated and needs to be replaced.

**Comment by vlad-penkin** [comment]
@pbchekin thanks for the troubleshooting and research. 

Does this workaround fix:
- #1004 
?

**Comment by pbchekin** [comment]
> @pbchekin thanks for the troubleshooting and research.
> 
> Does this workaround fix:
> 
> * [Build issue with Python 3.12 #1004](https://github.com/intel/intel-xpu-backend-for-triton/issues/1004)
> 
> ?

#1004 is about building triton, this one about running.

**Comment by riverliuintel** [comment]
stock PyTorch test BKC has sent to replace IPEX test proxy. This IPEX dependency has been removed. If met any questions in stock PyTorch test enabling, please let me know.

**Comment by vlad-penkin** [comment]
This is an IPEX issue, #925 makes it obsolete.
