### ISSUE TITLE
[PyTorch Upstream] Triton regression on Inductor test case:NameError("Cannot access global variable STRING_CONSTANT_C from within @jit'ed function)

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#1126]
When upgrade triton commit from dd072259e1df5c0cd42034d90ec5f464f22e5ae3 to e47fd9537aeb313cd048393ac50d71b25993ec56,
The Inductor test case used to pass now failed: 
```
python test/inductor/test_triton_kernels.py -k test_triton_kernel_constants

======================================================================
ERROR: test_triton_kernel_constants (__main__.KernelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xinanlin/xinanlin/pytorch/torch/testing/_internal/common_utils.py", line 2756, in wrapper
    method(*args, **kwargs)
  File "/home/xinanlin/xinanlin/pytorch/test/inductor/test_triton_kernels.py", line 637, in test_triton_kernel_constants
    torch_result = call_triton(t)
  File "/home/xinanlin/xinanlin/pytorch/test/inductor/test_triton_kernels.py", line 623, in call_triton
    mulC_kernel[grid](
  File "/home/xinanlin/xinanlin/miniconda3/lib/python3.10/site-packages/triton/runtime/jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/home/xinanlin/xinanlin/miniconda3/lib/python3.10/site-packages/triton/runtime/jit.py", line 662, in run
    kernel = self.compile(
  File "/home/xinanlin/xinanlin/miniconda3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 276, in compile
    module = src.make_ir(options, codegen_fns, context)
  File "/home/xinanlin/xinanlin/miniconda3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 113, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options, codegen_fns=codegen_fns)
triton.compiler.errors.CompilationError: at 13:30:
    in_ptr0,
    out_ptr,
    n_elements,
    BLOCK_SIZE: "tl.constexpr",
    CONSTANT_NAME: "tl.constexpr",
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(in_ptr0 + offsets, mask=mask)
    if CONSTANT_NAME.value == STRING_CONSTANT_C:
                              ^
NameError("Cannot access global variable STRING_CONSTANT_C from within @jit'ed function. Triton kernels can only access global variables that are annotated as
 constexpr (`x: triton.language.constexpr = 42` or `x = triton.language.constexpr(42)`).  Alternatively, set the envvar TRITON_ALLOW_NON_CONSTEXPR_GLOBALS=1,
but we do not promise to support this forever.")
```

### Reproduce:
checkout the PR: https://github.com/pytorch/pytorch/pull/124147
build stock Pytorch with USE_XPU=1
python test/inductor/test_triton_kernels.py -k test_triton_kernel_constants

**Comment by etaf** [comment]
@riverliuintel @vlad-penkin This issue block pytorch upstream, please priotize, thanks.

**Comment by alexbaden** [comment]
Will be fixed by https://github.com/pytorch/pytorch/pull/126195

**Comment by alexbaden** [comment]
Merged: https://github.com/pytorch/pytorch/commit/95543004362e3d1de20003cbb2e0c99e8b6606c4
