### ISSUE TITLE
[PyTorch Upstream] Inductor UT regression : TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#1220]
After update triton commit id in stock pytorch from `b8c64f64c18d8cac598b3adb355c21e7439c21de` to `b32c4d871602ff5b0b105cccaeaf3fc917de6abc`, we got inductor test case ` test/inductor/test_triton_kernels.py:KernelTests.test_triton_kernel_2d_autotune_grad_False_dynamic_False_backend_aot_eager_grid_type_1` failue when using python 3.8.

The error message:
```
2024-05-31T16:33:43.8626799Z This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
2024-05-31T16:33:43.8627300Z =================================== FAILURES ===================================
2024-05-31T16:33:43.8627856Z _ KernelTests.test_triton_kernel_2d_autotune_grad_False_dynamic_False_backend_aot_eager_grid_type_1 _
2024-05-31T16:33:43.8628374Z Traceback (most recent call last):
2024-05-31T16:33:43.8628829Z   File "inductor/test_triton_kernels.py", line 716, in test_triton_kernel_2d_autotune
2024-05-31T16:33:43.8629303Z     torch_result = call_triton(t1, t2, output)
2024-05-31T16:33:43.8629728Z   File "inductor/test_triton_kernels.py", line 709, in call_triton
2024-05-31T16:33:43.8630233Z     add_kernel_2d_autotuned[grid](x, y, output, x_elements, y_elements)
2024-05-31T16:33:43.8630949Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/triton/runtime/jit.py", line 345, in <lambda>
2024-05-31T16:33:43.8631639Z     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
2024-05-31T16:33:43.8632415Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/triton/runtime/autotuner.py", line 156, in run
2024-05-31T16:33:43.8633176Z     timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
2024-05-31T16:33:43.8633993Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/triton/runtime/autotuner.py", line 156, in <dictcomp>
2024-05-31T16:33:43.8634735Z     timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
2024-05-31T16:33:43.8635510Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/triton/runtime/autotuner.py", line 106, in _bench
2024-05-31T16:33:43.8636087Z     current = dict(meta, **config.all_kwargs())
2024-05-31T16:33:43.8636758Z   File "/opt/conda/envs/py_3.8/lib/python3.8/site-packages/triton/runtime/autotuner.py", line 242, in all_kwargs
2024-05-31T16:33:43.8637335Z     return self.kwargs | {
2024-05-31T16:33:43.8637751Z TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by alexbaden** [comment]
https://github.com/triton-lang/triton/pull/4049

**Comment by whitneywhtsang** [comment]
https://github.com/triton-lang/triton/commit/03b84666a1991a0addd6b0d80c911de98b7e6c31 merged in `llvm-target` by https://github.com/intel/intel-xpu-backend-for-triton/pull/1239.

**Comment by etaf** [comment]
Hi @whitneywhtsang  , is this issue  resolved?

**Comment by vlad-penkin** [comment]
@etaf  this merge fixes issue. To reiterate our statement - this is not a blocker issue, PyTorch 2.4 drops Python 3.8 support.
