### ISSUE TITLE
03-tutorial fails with upstream pytorch

### ISSUE THREAD

**Issue by ZzEeKkAa** [intel/intel-xpu-backend-for-triton#1496]
If using upstream torch + [xpu elapse time patch](https://github.com/pytorch/pytorch/pull/126456) applied, 03 tutorial fails to run with an error:

```
> python python/tutorials/03-matrix-multiplication.py
L0 build module failed. Log: 
Traceback (most recent call last):
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 390, in <module>
    triton_output = matmul(a, b)
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 370, in matmul
    matmul_kernel[grid](
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 327, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 156, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 156, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 133, in _bench
    return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/testing.py", line 139, in do_bench
    fn()
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 114, in kernel_call
    self.fn.run(
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 673, in run
    kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata, launch_metadata,
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 381, in __getattribute__
    self._init_handles()
  File "/localdisk/abaden/Projects/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 376, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.active.utils.load_binary(
RuntimeError: Triton Error [ZE]: 0x70000004
```

After digging further, it looks like particular autotuner configuration:
```
triton.Config({'BLOCK_SIZE_M': 256, 'BLOCK_SIZE_N': 512, 'BLOCK_SIZE_K': 64, 'GROUP_SIZE_M': 4}, num_stages=4,
                      num_warps=32),
```

If this line is commented out - issue is gone, however it does not answer the question why it is not working with upstream. So, after comparing upstream generated code and ipex generated code there is difference in the intel specific IR, while triton IR is the same. It looks like with upstream version device attribute was not set properly, I see `triton_gpu.target = "xpu:DEVICE_ARCH.UNKNOWN"` vs ipex `triton_gpu.target = "xpu:DEVICE_ARCH.PVC"`.

After investigating `third_party/intel/compiler.py` it looks like upstream version of pytorch does not populate two device flags, that most like defines how xpu device is recognized. By adding values from IPEX generated attributes, the example is working with upstream.

```
        target.arch['dev_type'] = 'gpu'
        target.arch['device_arch'] = 23
```

So the solution is to upstream `dev_type` and `device_arch` attributes to pytrorch.

**Comment by ZzEeKkAa** [comment]
No longer reproducable.
