### ISSUE TITLE
[compile-triton.sh] Fail on executing compile-triton.sh 

### ISSUE THREAD

**Issue by AshburnLee** [intel/intel-xpu-backend-for-triton#1538]
On the latest llvm-target branch, run `./scripts/compile-triton.sh --clean` and got:
```
**** BASE is not given *****
**** Default BASE is set to /home/jovyan/workspace ****
**** Cleaning /home/jovyan/workspace/packages, /home/jovyan/workspace/llvm, and /home/jovyan/workspace/intel-xpu-backend-for-triton/python/build before build ****
**** C_COMPILER is set to /usr/bin/gcc ****
**** CXX_COMPILER is set to /usr/bin/g++ ****
**** Configuring /home/jovyan/workspace/intel-xpu-backend-for-triton ****
Obtaining file:///home/jovyan/workspace/intel-xpu-backend-for-triton/python
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      downloading and extracting https://anaconda.org/nvidia/cuda-nvcc/12.4.99/download/linux-64/cuda-nvcc-12.4.99-0.tar.bz2 ...
      Traceback (most recent call last):
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-ly_l6d2c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-ly_l6d2c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-ly_l6d2c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-ly_l6d2c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-ly_l6d2c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 439, in <module>
        File "<string>", line 268, in download_and_copy
        File "<string>", line 199, in open_url
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/urllib/request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/urllib/request.py", line 525, in open
          response = meth(req, response)
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/urllib/request.py", line 634, in http_response
          response = self.parent.error(
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/urllib/request.py", line 563, in error
          return self._call_chain(*args)
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/urllib/request.py", line 496, in _call_chain
          result = func(*args)
        File "/home/jovyan/conda/envs/junhui-py310/lib/python3.10/urllib/request.py", line 643, in http_error_default
          raise HTTPError(req.full_url, code, msg, hdrs, fp)
      urllib.error.HTTPError: HTTP Error 429: Too Many Requests
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by pbchekin** [comment]
No longer reproducible.
