### ISSUE TITLE
[CI] [Conda Basekit build and test] compile pytorch and ipex error

### ISSUE THREAD

**Issue by AshburnLee** [intel/intel-xpu-backend-for-triton#1562]
I manually triggered `Conda Basekit build and test` and got this error: 
```
$SKIP_DEPS || $SCRIPTS_DIR/compile-pytorch-ipex.sh --pinned $ARGS
+ false
+ /runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/scripts/compile-pytorch-ipex.sh --pinned
**** BASE is not given *****
**** Default BASE is set to /runner/_work/intel-xpu-backend-for-triton ****
**** Determine if the installed PyTorch version is the same as the pinned version. ****
**** PyTorch is already installed and its current commit is equal to the pinned commit: 22ce6c6508d1d13b263d4c8b1fd6b98505983e92. ****
**** Determine if the installed IPEX version is the same as the pinned version. ****
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/miniforge3/envs/triton/lib/python3.9/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/home/runner/miniforge3/envs/triton/lib/python3.9/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /home/runner/miniforge3/envs/triton/lib/libmkl_sycl_data_fitting.so.4: undefined symbol: _ZN4sycl3_V17handler22setKernelIsCooperativeEb
```
ref: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/9787653292/job/27024486142

**Comment by leshikus** [comment]
There is a different error now, due to some dependency downloads. Need to fix it anyway

**Comment by vlad-penkin** [comment]
@leshikus is this issue fixed?

cc: @pbchekin

**Comment by pbchekin** [comment]
No longer reproducible.
