### ISSUE TITLE
Tutorials sample code throws Error: TypeError: an integer is required

### ISSUE THREAD

**Issue by cherngtar-intel** [intel/intel-xpu-backend-for-triton#1696]
Run tutorial sample code: /intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py

```
root@ace39ed84856:/app/intel-xpu-backend-for-triton/python/tutorials# python 01-vector-add.py
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/app/intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py", line 88, in <module>
    output_triton = add(x, y)
  File "/app/intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py", line 74, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "/app/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 326, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/app/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 588, in run
    device = driver.active.get_current_device()
  File "/app/intel-xpu-backend-for-triton/python/triton/backends/intel/driver.py", line 411, in get_current_device
    return self.utils.get_current_device()
  File "/app/intel-xpu-backend-for-triton/python/triton/backends/intel/driver.py", line 405, in __getattr__
    self.utils = XPUUtils()
  File "/app/intel-xpu-backend-for-triton/python/triton/backends/intel/driver.py", line 63, in __init__
    self.context = mod.init_context(self.get_sycl_queue())
TypeError: an integer is required
```

Trace in Pdb:
```
(Pdb) l
 59             dirname = os.path.dirname(os.path.realpath(__file__))
 60             mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "spirv_utils")
 61             self.load_binary = mod.load_binary
 62             self.get_device_properties = mod.get_device_properties
 63             import pdb; pdb.set_trace()
 64  ->         self.context = mod.init_context(self.get_sycl_queue())
 65             self.device_count = mod.init_devices(self.get_sycl_queue())
 66             self.current_device = 0 if self.device_count[0] > 0 else -1
 67
 68         def get_current_device(self):
 69             return self.current_device
(Pdb) self.get_sycl_queue()
<capsule object "torch.xpu.Stream.sycl_queue" at 0x7faef668bed0>
(Pdb) mod.init_context(self.get_sycl_queue())
*** TypeError: an integer is required
(Pdb) q
Traceback (most recent call last):
  File "/app/intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py", line 88, in <module>
    output_triton = add(x, y)
  File "/app/intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py", line 74, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "/app/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 326, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/app/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 588, in run
    device = driver.active.get_current_device()
  File "/app/intel-xpu-backend-for-triton/python/triton/backends/intel/driver.py", line 412, in get_current_d                                                                                                 evice
    return self.utils.get_current_device()
  File "/app/intel-xpu-backend-for-triton/python/triton/backends/intel/driver.py", line 406, in __getattr__
    self.utils = XPUUtils()
  File "/app/intel-xpu-backend-for-triton/python/triton/backends/intel/driver.py", line 64, in __init__
    self.context = mod.init_context(self.get_sycl_queue())
  File "/usr/lib/python3.10/bdb.py", line 96, in trace_dispatch
    return self.dispatch_exception(frame, arg)
  File "/usr/lib/python3.10/bdb.py", line 176, in dispatch_exception
```

**Comment by vlad-penkin** [comment]
@cherngtar-intel could you please provide information on your environment
- Agama Driver version
- Pytorch or IPEX version or commit id
- oneAPI Basekit or PyTorch Dependency bundle version
- GPU HW Model

**Comment by cherngtar-intel** [comment]
- intel-level-zero-gpu = 1.3.27642.40-803
- intel-extension-for-pytorch 2.1.30+xpu
- oneapi basekit - 2024.02
- Intel(R) Data Center GPU Flex 170

**Comment by AshburnLee** [comment]
@vlad-penkin Is our Triton target to Intel(R) Data Center GPU Flex 170 ? I thought it targets to **Max 1100** & **Max 1550** & **A770**.

**Comment by vlad-penkin** [comment]
@AshburnLee In terms of the HW GPU Flex 170 is equivalent to A770. 

Triton should work with some limitations on functionality (no DPAS with subgroup size = 8 support as of now) and performance (no DPAS with subgroup size = 8 support as of now) plus pytorch should be run in CPU fallback mode for FP64.

**Comment by vlad-penkin** [comment]
@cherngtar-intel few notes on your env
- You are using first LTS driver from January. There were seven LTS driver updates after it. Our recommendation is to switch to the latest Rolling Driver.
- IPEX is not supported. Please use upstream pytorch instead built from source with the last known good commit id  [pinned by Triton](https://github.com/intel/intel-xpu-backend-for-triton/blob/b039405939b19573f6e6eccd7bbeef375950341a/.github/pins/pytorch-upstream.txt#L1)  
- As of now Triton as well as PyTorch does not work with the regular oneAPI BaseKit. Please use [PyTorch dependency bundle ](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html#inpage-nav-1-1) instead.
