### ISSUE TITLE
issue when running 01-vector-add.py on docker WSL meteor-lake

### ISSUE THREAD

**Issue by abdulari** [intel/intel-xpu-backend-for-triton#1901]
hi.
I'm trying to run `01-vector-add.py` in docker WSL on Meteor Lake laptop, and failed for several times now.
hoping that you could tell me where I made a mistake.

```
docker run -it --rm --device /dev/dxg -v /mnt/c/0flex/triton-docker:/code --volume /usr/lib/wsl:/usr/lib/wsl my-local-registry/triton:test
```

```
# dockerfile
FROM intel/intel-optimized-pytorch:2.1.40-xpu
COPY intel-xpu-backend-for-triton /triton-src
RUN apt update && apt install -y python3-dev && pip install ninja cmake wheel
RUN cd /triton-src && ./scripts/compile-triton.sh --llvm --triton
```

```
export CXX=g++
root@d3b11130715f:/code/intel-xpu-backend-for-triton/python/tutorials# python 01-vector-add.py
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libpng16.so.16: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
In file included from /tmp/tmpulu9q8jk/main.cpp:17:
/usr/local/lib/python3.10/dist-packages/triton/backends/intel/include/sycl_functions.h:14:10: fatal error: sycl/sycl.hpp: No such file or directory
   14 | #include <sycl/sycl.hpp>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/code/intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py", line 88, in <module>
    output_triton = add(x, y)
  File "/code/intel-xpu-backend-for-triton/python/tutorials/01-vector-add.py", line 74, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 328, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 593, in run
    device = driver.active.get_current_device()
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/intel/driver.py", line 407, in get_current_device
    return self.utils.get_current_device()
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/intel/driver.py", line 401, in __getattr__
    self.utils = XPUUtils()
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/intel/driver.py", line 60, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "spirv_utils")
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/intel/driver.py", line 36, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dir, include_dir, libraries)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/build.py", line 73, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['g++', '/tmp/tmpulu9q8jk/main.cpp', '-shared', '-fPIC', '-o', '/tmp/tmpulu9q8jk/spirv_utils.cpython-310-x86_64-linux-gnu.so', '-lze_loader', '-lsycl', '-L/usr/local/lib/python3.10/dist-packages/triton/backends/intel/lib', '-I/usr/local/include', '-I/usr/local/lib/python3.10/dist-packages/triton/backends/intel/include', '-I/tmp/tmpulu9q8jk', '-I/usr/include/python3.10', '-I/usr/local/lib/python3.10/dist-packages/numpy/core/include']' returned non-zero exit status 1.
```

```
git clone https://github.com/intel/intel-xpu-backend-for-triton.git
git checkout 6590cf68ef7d6186be01b0d2f40b4fbc9973f951
```

**Comment by alexbaden** [comment]
It looks like `sycl` is not being found. Can you try using `icpx` instead of `g++`?

**Comment by alexbaden** [comment]
Also, by default you do not need `-llvm` in the compile triton script. A prebuilt LLVM will be downloaded and used by the Triton installer, which is invoked by the script. `--triton` is also true by default so that flag is not necessary.

**Comment by abdulari** [comment]
seems like icpx is not present in `intel/intel-optimized-pytorch:2.1.40-xpu` base container. will swap out to `https://hub.docker.com/r/intel/oneapi-basekit` and start from there.

will update if i got it working

**Comment by alexbaden** [comment]
You actually will want this version of the oneAPI base kit: https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html

I do not know if it is in a container or not.  You could try the oneAPI base kit container and then install the base kit from the link above using the offline installer, which will put the base kit in your home dir. but the container should have all the dependencies to make that smooth. You will also need gpu drivers from the same link.

**Comment by vlad-penkin** [comment]
@abdulari

Please capture and provide the details on the UMD part of the driver (`igc` and `level_zero` versions) by running this script - `./scripts/capture-hw-details.sh`

Triton will work only with:

1. [PyTorch Dependency Bundle](https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html) **not** regular oneAPI Basekit. Upstream PyTorch and Triton XPU will start supporting oneAPI Basekit starting from the 2025.0 release as per current plans.

2. Upstream PyTorch >= 2.4 with or without Triton specific pending PR's applied. Regilar IPEX is not supported as of now, we are in a process of deprecating dependency on special PT/IPEX 2.1 test proxies, we do not recommend to use those. 

3. Due MTL HW resource limitations please set env variable `MAX_JOBS` to 4 or 2.

To build Upstream PyTorch from source run the following script.

`./scripts/compile-pytorch-ipex.sh --pytorch --upstream-pytorch --source`

Our Tutorials code still have `import intel_extension_for_pytorch` line. You can either comment it out or install the dummy no-op ipex using this script:

```
from os import chdir, makedirs
from tempfile import TemporaryDirectory
from subprocess import run

with TemporaryDirectory() as tmpdir:
    pkg = "intel_extension_for_pytorch"
    chdir(tmpdir)
    makedirs(pkg, exist_ok=True)
    files = {
        f"{pkg}/__init__.py": "",
        "setup.py": (
            "from setuptools import setup, find_packages\n"
            f"setup(name='{pkg}', version='2', packages=find_packages())"
        ),
        "project.toml": (
            "[build-system]\n"
            "requires = [\"setuptools\", \"wheel\"]\n"
            "build-backend = \"setuptools.build_meta\""
        )
    }
    for file, content in files.items():
        with open(file, "w") as f:
            f.write(content)
    cmds = [
        f"pip uninstall -y {pkg}",
        "pip install build",
        "python -m build .",
        f"pip install dist/{pkg}-2-py3-none-any.whl"
    ]
    for cmd in cmds:
        run(cmd.split(), check=True)
```
