### ISSUE TITLE
[PyTorch pin update] `951c21d6` - Inductor tests are starting to fail after pybind11 update to 2.13.6

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2260]
PyTorch commit id: 951c21d6790334d57862e94a3f582ac724147a53
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10879914823/job/30185587514

```
_________ KernelTests.test_layout_constraint_needs_fixed_stride_order __________
Traceback (most recent call last):
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pytorch/test/inductor/test_triton_kernels.py", line 1072, in test_layout_constraint_needs_fixed_stride_order
    eager_out = f(x)
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pytorch/test/inductor/test_triton_kernels.py", line 1068, in f
    arange_out(x, y)
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pytorch/test/inductor/test_triton_kernels.py", line 1059, in arange_out
    kernel[grid](x, out, n_elements, BLOCK_SIZE=4)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/triton/runtime/jit.py", line 330, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/triton/runtime/jit.py", line 657, in run
    kernel = self.compile(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/triton/compiler/compiler.py", line 315, in compile
    metadata_group[metadata_filename] = fn_cache_manager.put(json.dumps(metadata, default=vars), metadata_filename,
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: vars() argument must have __dict__ attribute
```

**Comment by pbchekin** [comment]
CC @alexbaden

**Comment by anmyachev** [comment]
Reducing the number of potential problems: 
* db393fb95e5b057ca49472828bb6dba2db4f859e ([works](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10893104102/job/30227339671))

**Comment by pbchekin** [comment]
Do you think we can temporary pin pybind11 to the last working version?

**Comment by vlad-penkin** [comment]
Blocked by:
- https://github.com/pytorch/pytorch/pull/136280

**Comment by alexbaden** [comment]
pybind fix was merged last night/this morning, so this should also be resolved.

**Comment by anmyachev** [comment]
Removed in https://github.com/intel/intel-xpu-backend-for-triton/pull/2351
