### ISSUE TITLE
[PyTorch pin update] `f3c54ccf` - inductor/test_triton_wrapper.py::TestTritonWrapper::test_wrapper_using_gpu_seed 

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2301]
PyTorch commit id: f3c54ccf8f6139807f4623037c0174964a286652
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10955630000/job/30419929125

```
FAILED [0.3282s] inductor/test_triton_wrapper.py::TestTritonWrapper::test_wrapper_using_gpu_seed - torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
SubprocException: An exception occurred in a subprocess:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/torch/_inductor/compile_worker/subproc_pool.py", line 270, in do_job
    result = job()
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/torch/_inductor/runtime/compile_tasks.py", line 68, in _worker_compile_triton
    load_kernel().precompile(warm_cache_only=True)
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 244, in precompile
    compiled_binary, launcher = self._precompile_config(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/torch/_inductor/runtime/triton_heuristics.py", line 376, in _precompile_config
    ASTSource(
  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/triton/compiler/compiler.py", line 102, in __init__
    raise TypeError("Signature keys must be string")
TypeError: Signature keys must be string
```

**Comment by pbchekin** [comment]
FYI @anmyachev, @alexbaden

**Comment by anmyachev** [comment]
* 1a86d8aa29c8a67372f80d8f23cbfaa5b1b20f1e (failed): https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/10994409387/job/30522952424

**Comment by anmyachev** [comment]
Related to https://github.com/triton-lang/triton/pull/4693/files. Most likely, Triton changed the format, but PyTorch did not.

**Comment by alexbaden** [comment]
135406 was duplicated by https://github.com/pytorch/pytorch/pull/136514 which was merged - this issue should be resolved.
