### ISSUE TITLE
Torch does not work after installation from the wheels

### ISSUE THREAD

**Issue by Retribution98** [intel/intel-xpu-backend-for-triton#2393]
I installed torch from last wheel and it throw this exception once import torch:
```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ksuvorov/miniforge3/envs/intel-xpu-upstream/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    _load_global_deps()
  File "/home/ksuvorov/miniforge3/envs/intel-xpu-upstream/lib/python3.10/site-packages/torch/__init__.py", line 323, in _load_global_deps
    raise err
  File "/home/ksuvorov/miniforge3/envs/intel-xpu-upstream/lib/python3.10/site-packages/torch/__init__.py", line 300, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/ksuvorov/miniforge3/envs/intel-xpu-upstream/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
```

**Comment by vlad-penkin** [comment]
@Retribution98 can you provide `pip list` output for torch?

**Comment by arunjose696** [comment]
I assume this issue is due to oneAPI not being sourced. Because libmkl_intel_lp64.so.2 is present in oneapi directory

/opt/intel/oneapi/mkl/2025.0/lib/libmkl_intel_lp64.so.2 

Could you run with `source /opt/intel/oneapi/setvars.sh  --force ` or check if the file is absent in OneAPI installation?

**Comment by Retribution98** [comment]
It seems to be my specific issue because it was fixed the next day.
I thought it was an builds problem, but I checked a several last wheels and all of them now work for me.
