### ISSUE TITLE
Tutorial 08-grouped-gemm hangs on A770

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#2737]
### Describe the bug

https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/11888281266/job/33122520377#step:13:1039

### Environment details

GPU: A770

**Comment by anmyachev** [comment]
I saw the following error (before hanging):
```bash
~/intel-xpu-backend-for-triton/python$ python tutorials/08-grouped-gemm.py
Traceback (most recent call last):
  File ".../intel-xpu-backend-for-triton/python/tutorials/08-grouped-gemm.py", line 209, in <module>
    tri_out = group_gemm_fn(group_A, group_B)
  File ".../intel-xpu-backend-for-triton/python/tutorials/08-grouped-gemm.py", line 180, in group_gemm_fn
    grouped_matmul_kernel[grid](
  File ".../intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 330, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File ".../intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 189, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File ".../intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 189, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File ".../intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 167, in _bench
    return self.do_bench(kernel_call, quantiles=(0.5, 0.2, 0.8))
  File ".../intel-xpu-backend-for-triton/python/triton/testing.py", line 202, in do_bench
    cache.zero_()
RuntimeError: UR backend failed. UR backend returns:40 (UR_RESULT_ERROR_OUT_OF_RESOURCES)

```

**Comment by pbchekin** [comment]
Reopening since the tutorials hangs again: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/12501473319/job/34895686819.

**Comment by anmyachev** [comment]
@arunjose696 FYI, even though I removed the tutorial from the list of skipped issues, I don't plan to close this issue, considering it has already been reopened. I suggest monitoring the tutorial for another week before closing this issue.

**Comment by pbchekin** [comment]
Looks like the tutorial works both on linux and windows for several weeks. Closing this issue, will open a new one if the problem persists.
