### ISSUE TITLE
Inductor UT break on Triton: error: undefined reference to `__builtin_spirv_OpAtomicFAddEXT_p1f16_i32_i32_f16'

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#282]
# Issue Description

Inductor UT break on Triton: error: undefined reference to `__builtin_spirv_OpAtomicFAddEXT_p1f16_i32_i32_f16'
```
L0 build module failed. Log:

error: undefined reference to `__builtin_spirv_OpAtomicFAddEXT_p1f16_i32_i32_f16'
in function: '_builtin_spirv_OpAtomicFAddEXT_p1f16_i32_i32_f16' called by kernel: 'triton_0d1d2'

error: backend compiler failed build.

[2024-01-12 00:37:59,295] torch.inductor.debug: [WARNING] model_0 debug trace: /home/xinanlin/xinanlin/pytorch/torch_compile_debug/run_2024_01_12_00_37_59
027212-pid_849227/torchinductor/model___0.0
Traceback (most recent call last):
  File "/home/xinanlin/xinanlin/pytorch/torch_compile_debug/run_2024_01_12_00_20_44_554706-pid_504980/torchinductor/model__0_backward_57.1/fx_graph_runnable.p
y", line 52, in <module>
    run_repro(mod, load_args, accuracy=False, command='run', save_dir=None, tracing_mode='real', check_str=None)
  File "/home/xinanlin/xinanlin/pytorch/torch/_dynamo/repro/after_aot.py", line 927, in run_repro
    COMMAND_FNS[options.command](options, mod, load_args)
  File "/home/xinanlin/xinanlin/pytorch/torch/_dynamo/repro/after_aot.py", line 688, in repro_run
    compiled = compile_fx_inner(mod, args)
  File "/home/xinanlin/xinanlin/pytorch/torch/_dynamo/repro/after_aot.py", line 80, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/debug.py", line 228, in inner
    return fn(*args, **kwargs)
  File "/home/xinanlin/miniconda3/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/compile_fx.py", line 54, in newFunction
    return old_func(*args, **kwargs)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/compile_fx.py", line 341,

   compiled_graph: CompiledFxGraph = fx_codegen_and_compile(
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/compile_fx.py", line 565, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/graph.py", line 981, in compile_to_fn
    return self.compile_to_module().call
  File "/home/xinanlin/xinanlin/pytorch/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/graph.py", line 952, in compile_to_module
    mod = PyCodeCache.load_by_key_path(key, path, linemap=linemap)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/codecache.py", line 1143, in load_by_key_path
    exec(code, mod._dict, mod.dict_)
  File "/tmp/torchinductor_xinanlin/p6/cp6bsnp7m65kjxpmqlr6ekparze7n55iapke34xovdcn4jcrztyd.py", line 56, in <module>
    triton_poi_fused_1 = async_compile.triton('triton_', '''
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/codecache.py", line 1404, in triton
    return _load_kernel(kernel_name, source_code)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/codecache.py", line 1274, in _load_kernel
    kernel.precompile()
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/triton_heuristics.py", line 180, in precompile
    self.launchers = [
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/triton_heuristics.py", line 181, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/xinanlin/xinanlin/pytorch/torch/_inductor/triton_heuristics.py", line 219, in _precompile_config
    binary._init_handles()
  File "/home/xinanlin/miniconda3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 570, in _init_handles
    mod, func, n_regs, n_spills = fn_load_binary(self.metadata["name"], self.asm[bin_path], self.shared, device)
  File "/home/xinanlin/miniconda3/lib/python3.10/site-packages/triton/third_party/xpu/_init_.py", line 415, in _load_binary_fn
    return self.driver.utils.load_binary(kernel_name, binary, shared_size, torch.xpu.device(device).sycl_device)  # noqa: E501
RuntimeError: L0 API error code: 70000004
 in compile_fx_inner
```
# Code Example

```python

import torch
import intel_extension_for_pytorch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
import torch._inductor.inductor_prims

import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config
torch._dynamo.config.raise_on_unsafe_aot_autograd = True
torch._inductor.config.implicit_fallbacks = False
torch._inductor.config.triton.autotune_pointwise = False



isolate_fails_code_str = None



# torch version: 2.1.0a0+gita545ebf
# torch cuda version: None
# torch git version: a545ebf33472f165c20b85a0678a633c2cc3ab30


# torch.cuda.is_available()==False, no GPU info collected

from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('_tensor_constant0', tensor([1, 2], device='xpu:0'))

    
    
    def forward(self, tangents_1):
        _tensor_constant0 = self._tensor_constant0
        lift_fresh_copy = torch.ops.aten.lift_fresh_copy.default(_tensor_constant0);  _tensor_constant0 = None
        full_default = torch.ops.aten.full.default([5, 5, 5], 0, dtype = torch.float16, layout = torch.strided, device = device(type='xpu', index=0), pin_memory = False)
        index_put = torch.ops.aten.index_put.default(full_default, [lift_fresh_copy], tangents_1, True);  full_default = lift_fresh_copy = tangents_1 = None
        return [index_put]
        
def load_args(reader):
    buf0 = reader.storage(None, 100, device=device(type='xpu', index=0), dtype_hint=torch.float16)
    reader.tensor(buf0, (2, 5, 5), dtype=torch.float16, is_leaf=True)  # tangents_1
load_args._version = 0
mod = Repro()
if __name__ == '__main__':
    from torch._dynamo.repro.after_aot import run_repro
    run_repro(mod, load_args, accuracy=False, command='run', save_dir=None, tracing_mode='real', check_str=None)
```
# System Info
- OS: Linux
- PyTorch: Public Pytorch release 2.1： a545ebf33472f165c20b85a0678a633c2cc3ab30
  
- Intel Extension For Pytorch: nternal master: 091e1e2ae2317fd63da6a0d58d6dd73f9ce76a58
  
- LLVM Version.
  
- Triton Version: release 2.1: https://github.com/intel/intel-xpu-backend-for-triton/releases/download/v2.1.0/triton-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  
- Intel® XPU Backend for Triton*:

**Comment by vlad-penkin** [comment]
@etaf is this issue reproducible for the llvm-spirv branch?

**Comment by etaf** [comment]
> @etaf is this issue reproducible for the llvm-spirv branch?
Hi @vlad-penkin , we only test with wheel package (Triton release 2.1 with intel xpu backend), not sure if it work on the llvm-spirv branch.

**Comment by vlad-penkin** [comment]
The issue is reproducible with the llvm-target branch

[2024-02-14 16:12:52,722] torch._dynamo.debug_utils: [WARNING] no save_dir specified, will generate random data
[2024-02-14 16:12:52,722] torch._dynamo.debug_utils: [WARNING] could not load None, generating random data instead
Loading inputs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 249.74it/s]
InvalidModule: Invalid SPIR-V module: input SPIR-V module uses unknown extension 'SPV_EXT_shader_atomic_float16_add'

**Comment by etiotto** [comment]
The SPIRV operation  'SPV_EXT_shader_atomic_float16_add' is generated because the LLVM IR contains the following atomic RMW using operands that have `f16` datatype (half in LLVM IR terms):

  %86 = atomicrmw fadd ptr addrspace(1) %78, half %85 acq_rel, align 2, !dbg !22
  
IGC consider that operation invalid.

**Comment by etiotto** [comment]
The issue here is that `AtomicFloat16AddEXT` in the [SPIRV specification](https://spec.oneapi.io/level-zero/latest/core/SPIRV.html#atomic-add-and-subtract) can be used only if the environment supports f16 atomics (ze_device_fp_atomic_ext_flags_t.fp16Flags contains *_ADD flag).  

This implies that the Triton compiler cannot generate an atomicrmw instruction on float16 data types if the target GPU does not support atomic operations on that data type. There are a couple of solutions I can think of:
  1. the Triton compiler generates atomicrmw (for f16) only if the target GPU supports that feature 
  2. the LLVM-SPIRV translator query the environment and determines how to lower an atomicrmw appropriately 
  
  I am inclined on using solution 1.

**Comment by vlad-penkin** [comment]
Duplicates
- #728
