### ISSUE TITLE
Inductor UT break on Triton "error: 'spirv.module' cannot contain external functions without 'Import' linkage_attributes (LinkageAttributes)"

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#283]
# Issue Description

Inductor UT break on Triton "error: 'spirv.module' cannot contain external functions without 'Import' linkage_attributes (LinkageAttributes)"
```
error: 'spirv.module' cannot contain external functions without 'Import' linkage_attributes (LinkageAttributes)
Translate to SPIRV IR failedTraceback (most recent call last):
  File "/home/sdp/xinanlin/test_index1.py", line 26, in <module>
    triton_poi_fused_index_0 = async_compile.triton('triton_', '''
  File "/home/sdp/xinanlin/ipex/intel_extension_for_pytorch/_inductor/xpu/codecache.py", line 73, in triton
    return _load_kernel(kernel_name, source_code)
  File "/home/sdp/xinanlin/pytorch/torch/_inductor/codecache.py", line 1274, in _load_kernel
    kernel.precompile()
  File "/home/sdp/xinanlin/pytorch/torch/_inductor/triton_heuristics.py", line 174, in precompile
    self.launchers = [
  File "/home/sdp/xinanlin/pytorch/torch/_inductor/triton_heuristics.py", line 175, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/sdp/xinanlin/ipex/intel_extension_for_pytorch/_inductor/xpu/triton_heuristics.py", line 93, in _precompile_config
    binary = triton.compile(
  File "/home/sdp/miniconda3/envs/xinanlin/lib/python3.10/site-packages/triton/compiler/compiler.py", line 476, in compile
    next_module = compile_kernel(module)
  File "/home/sdp/miniconda3/envs/xinanlin/lib/python3.10/site-packages/triton/third_party/xpu/__init__.py", line 381, in <lambda>
    lambda src: ttgir_to_spirv(src, extern_libs, arch))
  File "/home/sdp/miniconda3/envs/xinanlin/lib/python3.10/site-packages/triton/third_party/xpu/__init__.py", line 35, in ttgir_to_spirv
    spirv_code, share_memory_size = _triton.translate_triton_gpu_to_spirv(str(mod), arch)  # noqa: E501
RuntimeError: Failed to translate TritonGPU to SPIRV IR.
```
# Code Example

```python
from ctypes import c_void_p, c_long
import torch
import intel_extension_for_pytorch
import math
import random
import os
import tempfile
from math import inf, nan
from torch._inductor.hooks import run_intermediate_hooks
from torch._inductor.utils import maybe_profile

from torch import empty_strided, device
from intel_extension_for_pytorch._inductor.xpu.codecache import XPUAsyncCompile 
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
reinterpret_tensor = torch.ops.inductor._reinterpret_tensor
async_compile = XPUAsyncCompile()


# kernel path: /tmp/torchinductor_xinanlin/ml/cmlxqokkq4zbpj3aekin7rlpz3ybmddtikyqgm7qynejzmsxdrws.py
# Source Nodes: [index], Original ATen: [aten.index]
# index => index
triton_poi_fused_index_0 = async_compile.triton('triton_', '''
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from intel_extension_for_pytorch._inductor.xpu.triton_heuristics import AutotuneHint, pointwise

from torch._inductor.utils import instance_descriptor
from torch._inductor import triton_helpers

@pointwise(size_hints=[64], filename=__file__, meta={'signature': {0: '*i64', 1: '*i64', 2: '*fp32', 3: '*fp32', 4: 'i32'}, 'device': 0, 'device_type': 'xpu', 'constants': {}, 'mutated_arg_names': [], 'autotune_hints': set(), 'kernel_name': 'triton_poi_fused_index_0', 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2, 3, 4), equal_to_1=(), ids_of_folded_args=(), divisible_by_8=(4,))]})
@triton.jit
def triton_(in_ptr0, in_ptr1, in_ptr2, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 48
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x1 = (xindex // 12)
    x0 = xindex % 12
    x2 = xindex
    tmp0 = tl.load(in_ptr0 + (x1), xmask, eviction_policy='evict_last')
    tmp2 = tl.load(in_ptr1 + (x1), xmask, eviction_policy='evict_last')
    tmp1 = tl.where(tmp0 < 0, tmp0 + 8, tmp0)
    tl.device_assert(((0 <= tmp1) & (tmp1 < 8)) | ~xmask, "index out of bounds: 0 <= tmp1 < 8")
    tmp3 = tl.where(tmp2 < 0, tmp2 + 8, tmp2)
    tl.device_assert(((0 <= tmp3) & (tmp3 < 8)) | ~xmask, "index out of bounds: 0 <= tmp3 < 8")
    tmp4 = tl.load(in_ptr2 + (x0 + (12*tmp3) + (96*tmp1)), xmask)
    tl.store(out_ptr0 + (x2), tmp4, xmask)
''')

import triton
import triton.language as tl
from torch._inductor.triton_heuristics import grid, start_graph, end_graph
from intel_extension_for_pytorch._C import _getCurrentRawStream as get_raw_stream


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, arg1_1, arg2_1 = args
    args.clear()
    assert_size_stride(arg0_1, (8, 8, 12), (96, 12, 1))
    assert_size_stride(arg1_1, (4, ), (1, ))
    assert_size_stride(arg2_1, (4, ), (1, ))
    with torch.xpu._DeviceGuard(0):
        torch.xpu.set_device(0)
        buf0 = empty_strided((4, 12), (12, 1), device='xpu', dtype=torch.float32)
        # Source Nodes: [index], Original ATen: [aten.index]
        stream0 = get_raw_stream(0)
        triton_poi_fused_index_0.run(arg1_1, arg2_1, arg0_1, buf0, 48, grid=grid(48), stream=stream0)
        run_intermediate_hooks('index', buf0)
        del arg0_1
        del arg1_1
        del arg2_1
        return (buf0, )


def benchmark_compiled_module(times=10, repeat=10):
    from torch._dynamo.testing import rand_strided
    from torch._inductor.utils import print_performance
    arg0_1 = rand_strided((8, 8, 12), (96, 12, 1), device='xpu:0', dtype=torch.float32)
    arg1_1 = rand_strided((4, ), (1, ), device='xpu:0', dtype=torch.int64)
    arg2_1 = rand_strided((4, ), (1, ), device='xpu:0', dtype=torch.int64)
    return print_performance(lambda: call([arg0_1, arg1_1, arg2_1]), times=times, repeat=repeat)


if __name__ == "__main__":
    #from torch._inductor.wrapper_benchmark import compiled_module_main
    from intel_extension_for_pytorch._inductor.xpu.wrapper_benchmark import compiled_module_main
    compiled_module_main('None', benchmark_compiled_module)

```
# System Info
- OS: Linux
- PyTorch: Public Pytorch release 2.1： a545ebf33472f165c20b85a0678a633c2cc3ab30
  
- Intel Extension For Pytorch: nternal master: 091e1e2ae2317fd63da6a0d58d6dd73f9ce76a58
  
- LLVM Version.
  
- Triton Version: release 2.1: https://github.com/intel/intel-xpu-backend-for-triton/releases/download/v2.1.0/triton-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
  
- Intel® XPU Backend for Triton*:

**Comment by vlad-penkin** [comment]
@etaf is this issue reproducible for Pytorch main and Triton llvm-target branch?

**Comment by etaf** [comment]
> @etaf is this issue reproducible for Pytorch main and Triton llvm-target branch?

Hi @vlad-penkin , we only test with wheel package (Triton release 2.1 with intel xpu backend), not sure if it work on the llvm-spirv branch.

**Comment by vlad-penkin** [comment]
Triton release 2.1 with intel xpu backend was built with a legacy spriv branch.
