### ISSUE TITLE
RuntimeError (IGC: LLVM Error: Diag: aborted) on MTL and ARL

### ISSUE THREAD

**Issue by kwasd** [intel/intel-xpu-backend-for-triton#3003]
When starting benchmarks, for MTL and ARL there is same error

```
ZE_LOADER_DEBUG_TRACE:Using Loader Library Path: 
23ZE_LOADER_DEBUG_TRACE:Tracing Layer Library Path: libze_tracing_layer.so.1 
24/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.10.15/lib/python3.10/site-packages/triton_kernels_benchmark-3.1.0+gitb57f1b51-py3.10-linux-x86_64.egg/triton_kernels_benchmark/benchmark_testing.py:29: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at /runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pytorch/aten/src/ATen/native/ReduceOps.cpp:1831.) 
25 std = torch.std(times) 
26Traceback (most recent call last): 
27 File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/fused_softmax.py", line 170, in <module> 
28 benchmark.run(show_plots=False, print_data=True) 
29 File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.10.15/lib/python3.10/site-packages/triton_kernels_benchmark-3.1.0+gitb57f1b51-py3.10-linux-x86_64.egg/triton_kernels_benchmark/benchmark_testing.py", line 454, in run 
30 result_dfs.append(self._run(bench, save_path, show_plots, print_data, **kwargs)) 
31 File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.10.15/lib/python3.10/site-packages/triton_kernels_benchmark-3.1.0+gitb57f1b51-py3.10-linux-x86_64.egg/triton_kernels_benchmark/benchmark_testing.py", line 388, in _run 
32 ret = self.fn(**x_args, **{bench.line_arg: y}, **bench.args, **kwrags) 
33 File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/fused_softmax.py", line 157, in benchmark 
34 _, min_ms, max_ms, mean, cv = benchmark_suit.do_bench(xetla_fn, quantiles=quantiles, n_warmup=10, n_repeat=10, 
35 File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/pyenv/versions/3.10.15/lib/python3.10/site-packages/triton_kernels_benchmark-3.1.0+gitb57f1b51-py3.10-linux-x86_64.egg/triton_kernels_benchmark/benchmark_testing.py", line 143, in do_bench_elapsed_time 
36 fn() 
37 File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/benchmarks/triton_kernels_benchmark/fused_softmax.py", line 145, in <lambda> 
38 xetla_fn = lambda: func(x, out, 0) 
39RuntimeError: The program was built for 1 devices 
40Build program log for 'Intel(R) Arc(TM) Graphics': 
41IGC: LLVM Error: Diag: aborted
```

Environment details
Ubuntu 24.10
GCC 14.2.0
Python 3.10
DLE 2025.0.0.345

Discovered while #2522. 
Maybe related to https://github.com/intel-analytics/ipex-llm/issues/11843

**Comment by alexbaden** [comment]
This looks like a xeTLA issue. Maybe someone from @tdeng5 's team can help?

**Comment by alexbaden** [comment]
We want to run these benchmarks for Triton but not XeTLA on MTL and ARL. Once that is running in CI we can close this issue, we won't pursue a fix for the XeTLA issue right now.

**Comment by vlad-penkin** [comment]
@kwasd can we close this ticket?

**Comment by kwasd** [comment]
will check

**Comment by januszjah** [comment]
> will check

did u check?
