### ISSUE TITLE
Random 08-grouped-gemm.py tutorial hangs on MTL and ARL

### ISSUE THREAD

**Issue by kwasd** [intel/intel-xpu-backend-for-triton#3004]
Sometimes run hangs when running `08-grouped-gemm.py`.

While hangs, these messages appear in dmesg:

```
[851670.689888] Fence expiration time out i915-0000:00:02.0:python3[744499]:3b52!
[865794.039663] Fence expiration time out i915-0000:00:02.0:python[767018]:124!
[865794.055655] Fence expiration time out i915-0000:00:02.0:python[767018]:12a!
[865794.055912] Fence expiration time out i915-0000:00:02.0:python[767018]:128!
```

Environment details

Ubuntu 24.10
GCC 14.2.0
Python 3.10
Current pinned pytorch (61dc5e9c0a36d590adc47b4110efd94d9eb59306)
Onnx 1014f41f (pinned) or 30896d (bumped)
DLE 2025.0.0.345
Linux 6.11.0-9-generic

Discovered while #2522

**Comment by anmyachev** [comment]
After updating Pytorch pin, it does not build on these systems. @kwasd @pbchekin do you know why?

```bash
.../intel-xpu-backend-for-triton/pytorch/aten/src/ATen/native/DispatchStub.cpp:152:18: error: no matching function for call to ‘find(std::array<c10::DeviceType, 7>::const_iterator, std::array<c10::DeviceType, 7>::const_iterator, const c10::DeviceType&)’
  152 |     if (std::find(supported_devices.begin(), supported_devices.end(), device_type) == supported_devices.end()) {
      |         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/14/bits/locale_facets.h:48,
                 from /usr/include/c++/14/bits/basic_ios.h:37,
                 from /usr/include/c++/14/ios:46,
                 from /usr/include/c++/14/ostream:40,
```

**Comment by pbchekin** [comment]
> After updating Pytorch pin, it does not build on these systems. [@kwasd](https://github.com/kwasd) [@pbchekin](https://github.com/pbchekin) do you know why?

I think it is because of gcc 14 vs gcc 11 (ot other systems).

**Comment by anmyachev** [comment]
> > After updating Pytorch pin, it does not build on these systems. [@kwasd](https://github.com/kwasd) [@pbchekin](https://github.com/pbchekin) do you know why?
> 
> I think it is because of gcc 14 vs gcc 11 (ot other systems).

Most likely, you are right: https://github.com/apache/arrow/pull/40010. I will try this fix.

**Comment by anmyachev** [comment]
Now the error is due to OOM I guess: `collect2: fatal error: ld terminated with signal 9 [Killed]`.

**Comment by anmyachev** [comment]
New issue:

```bash
sycl_arch not recognized: 297796608
Traceback (most recent call last):
  File ".../intel-xpu-backend-for-triton/scripts/run_tutorial.py", line 71, in <module>
    main()
  File ".../intel-xpu-backend-for-triton/scripts/run_tutorial.py", line 67, in main
    run_tutorial(tutorial_path)
  File ".../intel-xpu-backend-for-triton/scripts/run_tutorial.py", line 50, in run_tutorial
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "08-grouped-gemm.py", line 215, in <module>
    assert torch.allclose(ref_out[i], tri_out[i], atol=1e-4, rtol=1e-3)
AssertionError
```

**Comment by anmyachev** [comment]
Moreover, tutorial `03-matrix-multiplication` also fails the accuracy test:
```bash
triton_output_with_fp16_inputs=tensor([[ 12.8594,  -1.6064,   8.5156,  ...,   7.1055, -27.9062,  12.1484],
        [-18.4688,   0.8447,  18.0156,  ..., -22.4844, -42.5625, -46.2500],
        [-26.7812,  20.6094,   8.7500,  ...,  28.6250,  23.3438, -25.0312],
        ...,
        [  7.0898,  43.7188,   1.2266,  ..., -46.4375, -15.5781,   8.6484],
        [-36.5312,  25.8125, -47.6250,  ..., -21.2812,   8.1562, -24.7031],
        [ -0.9038,   1.3008, -29.7812,  ...,   0.9043,  11.6641, -14.[921](https://github.com/intel-innersource/applications.python.intel-xpu-backend-for-triton/actions/runs/13370393593/job/37337429329#step:15:922)9]],
       device='xpu:0', dtype=torch.float16)
torch_output_with_fp16_inputs=tensor([[ 12.8750,  -1.6045,   8.5547,  ...,   7.1445, -28.0938,  12.0859],
        [-18.4844,   0.8203,  18.0312,  ..., -22.4688, -42.5000, -46.1250],
        [-26.8125,  20.5156,   8.7422,  ...,  28.6250,  23.3906, -25.0938],
        ...,
        [  7.0352,  43.5938,   1.1855,  ..., -46.4375, -15.4766,   8.6875],
        [-36.5000,  25.6094, -47.6562,  ..., -21.1719,   8.1641, -24.6875],
        [ -0.9287,   1.2764, -29.8750,  ...,   0.9297,  11.6797, -14.9688]],
       device='xpu:0', dtype=torch.float16)
❌ Triton and Torch differ
```
