### ISSUE TITLE
[Windows][Pytorch Upstream] Triton do_bench returns time not greater than 0.

### ISSUE THREAD

**Issue by etaf** [intel/intel-xpu-backend-for-triton#3072]
### Describe the bug

The timing from triton's `do_bench` returns a number not greater than 0 on windows.
The error:
```
(xinanlin) C:\xinanlin\pytorch>python test\inductor\test_benchmarking.py -vf
test_benchmark_cpu_smoke_benchmarker_cls0 (__main__.TestBenchmarker) ... inductor [('benchmarking.Benchmarker.benchmark_cpu', 1)]
ok
test_benchmark_cpu_smoke_benchmarker_cls1 (__main__.TestBenchmarker) ... inductor [('benchmarking.TritonBenchmarker.benchmark_cpu', 1)]
ok
test_benchmark_gpu_smoke_benchmarker_cls0 (__main__.TestBenchmarker) ... inductor [('benchmarking.Benchmarker.benchmark_gpu', 1)]
expected failure
test_benchmark_gpu_smoke_benchmarker_cls1 (__main__.TestBenchmarker) ... inductor [('benchmarking.TritonBenchmarker.benchmark_gpu', 1), ('benchmarking.TritonBenchmarker.triton_do_bench', 1)]
FAIL

======================================================================
FAIL: test_benchmark_gpu_smoke_benchmarker_cls1 (__main__.TestBenchmarker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 3108, in wrapper
    method(*args, **kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 557, in instantiated_test
    test(self, **param_kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 840, in test_wrapper
    return test(*args, **kwargs)
  File "C:\xinanlin\pytorch\test\inductor\test_benchmarking.py", line 82, in test_benchmark_gpu_smoke
    self.assertGreater(timing, 0)
AssertionError: -1.3166919946670532 not greater than 0

To execute this test, run the following from the base repo dir:
    python test\inductor\test_benchmarking.py TestBenchmarker.test_benchmark_gpu_smoke_benchmarker_cls1

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 4 tests in 0.592s

FAILED (failures=1, expected failures=1)
```

The `benchmark` use Triton's `do_bench` as follow:
https://github.com/pytorch/pytorch/blob/6bdf2addc5e83cdf67af1261c417b3c91104ad02/torch/_inductor/runtime/benchmarking.py#L181-L202

### Environment details

Latest Triton main branch and stock PyTorch main branch.

**Comment by anmyachev** [comment]
Hi @etaf!

Could you try https://github.com/intel/intel-xpu-backend-for-triton/commit/8bd80f6da4e2c4c313ea2d1f6b69bc108d4762ed? If it works for you, I'll add it to the branch with Windows fixes.

**Comment by etaf** [comment]
> Hi [@etaf](https://github.com/etaf)!
> 
> Could you try [8bd80f6](https://github.com/intel/intel-xpu-backend-for-triton/commit/8bd80f6da4e2c4c313ea2d1f6b69bc108d4762ed)? If it works for you, I'll add it to the branch with Windows fixes.

I've tried but got other error:
```
(xinanlin) C:\xinanlin\pytorch>git apply ..\triton\scripts\pytorch.patch

(xinanlin) C:\xinanlin\pytorch>python test\inductor\test_benchmarking.py TestBenchmarker.test_benchmark_gpu_smoke_benchmarker_cls1
WARNING:root:Wall time is used instead of elapsed_time (not supported).         The timing measurements could be innacurate.
inductor [('benchmarking.TritonBenchmarker.benchmark_gpu', 1), ('benchmarking.TritonBenchmarker.triton_do_bench', 1)]
E
======================================================================
ERROR: test_benchmark_gpu_smoke_benchmarker_cls1 (__main__.TestBenchmarker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 3114, in wrapper
    method(*args, **kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 557, in instantiated_test
    test(self, **param_kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 840, in test_wrapper
    return test(*args, **kwargs)
  File "C:\xinanlin\pytorch\test\inductor\test_benchmarking.py", line 81, in test_benchmark_gpu_smoke
    timing = benchmarker.benchmark_gpu(_callable)
  File "c:\xinanlin\pytorch\torch\_inductor\runtime\benchmarking.py", line 66, in wrapper
    return fn(self, *args, **kwargs)
  File "c:\xinanlin\pytorch\torch\_inductor\runtime\benchmarking.py", line 202, in benchmark_gpu
    return self.triton_do_bench(_callable, **kwargs, return_mode="median")
  File "c:\xinanlin\triton\python\triton\testing.py", line 227, in do_bench
    triton.runtime.driver.active.utils.wait()
  File "c:\xinanlin\triton\python\triton\runtime\driver.py", line 24, in __getattr__
    return getattr(self._obj, name)
  File "c:\xinanlin\triton\python\triton\backends\intel\driver.py", line 607, in __getattr__
    self.utils = XPUUtils()
  File "c:\xinanlin\triton\python\triton\backends\intel\driver.py", line 174, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "spirv_utils")
  File "c:\xinanlin\triton\python\triton\backends\intel\driver.py", line 148, in compile_module_from_src
    extra_compiler_args += ['-Wl,-rpath,' + COMPILATION_HELPER.libsycl_dir]
TypeError: can only concatenate str (not "tuple") to str

To execute this test, run the following from the base repo dir:
    python test\inductor\test_benchmarking.py TestBenchmarker.test_benchmark_gpu_smoke_benchmarker_cls1

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 0.401s

FAILED (errors=1)
```

Can you try to run this test in your side? BTW, does this fix works for BMG?

**Comment by anmyachev** [comment]
> I've tried but got other error:

This is a regression, we already have a fix for this in https://github.com/intel/intel-xpu-backend-for-triton/pull/3193.

> Can you try to run this test in your side?

Unfortunately, I don't have the necessary environment.

> BTW, does this fix works for BMG?

We tried to run benchmarking (not PyTorch tests) and we got positive numbers.

**Comment by etaf** [comment]
> > I've tried but got other error:
> 
> This is a regression, we already have a fix for this in [#3193](https://github.com/intel/intel-xpu-backend-for-triton/pull/3193).
> 
> > Can you try to run this test in your side?
> 
> Unfortunately, I don't have the necessary environment.
> 
> > BTW, does this fix works for BMG?
> 
> We tried to run benchmarking (not PyTorch tests) and we got positive numbers.
> 
> **UPD:** please note that Windows tests currently only work if there is `icpx` in the path.

Thanks @anmyachev , sorry for the late reply, my Windows environment has been messed up by someone. I've rebuild and tried your fix but still get errors:
```
(xinanlin) C:\xinanlin\pytorch>python test\inductor\test_benchmarking.py TestBenchmarker.test_benchmark_gpu_smoke_benchmarker_cls1
icpx: error: linker command failed with exit code 1181 (use -v to see invocation)
WARNING:root:Wall time is used instead of elapsed_time (not supported).         The timing measurements could be innacurate.
icpx: error: linker command failed with exit code 1181 (use -v to see invocation)
inductor [('benchmarking.TritonBenchmarker.benchmark_gpu', 1), ('benchmarking.TritonBenchmarker.triton_do_bench', 1)]
E
======================================================================
ERROR: test_benchmark_gpu_smoke_benchmarker_cls1 (__main__.TestBenchmarker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 3114, in wrapper
    method(*args, **kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 557, in instantiated_test
    test(self, **param_kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 840, in test_wrapper
    return test(*args, **kwargs)
  File "C:\xinanlin\pytorch\test\inductor\test_benchmarking.py", line 81, in test_benchmark_gpu_smoke
    timing = benchmarker.benchmark_gpu(_callable)
  File "c:\xinanlin\pytorch\torch\_inductor\runtime\benchmarking.py", line 66, in wrapper
    return fn(self, *args, **kwargs)
  File "c:\xinanlin\pytorch\torch\_inductor\runtime\benchmarking.py", line 202, in benchmark_gpu
    return self.triton_do_bench(_callable, **kwargs, return_mode="median")
  File "c:\xinanlin\triton\python\triton\testing.py", line 227, in do_bench
    triton.runtime.driver.active.utils.wait()
  File "c:\xinanlin\triton\python\triton\runtime\driver.py", line 24, in __getattr__
    return getattr(self._obj, name)
  File "c:\xinanlin\triton\python\triton\backends\intel\driver.py", line 607, in __getattr__
    self.utils = XPUUtils()
  File "c:\xinanlin\triton\python\triton\backends\intel\driver.py", line 174, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "spirv_utils")
  File "c:\xinanlin\triton\python\triton\backends\intel\driver.py", line 149, in compile_module_from_src
    so = _build(name, src_path, tmpdir, COMPILATION_HELPER.library_dir, COMPILATION_HELPER.include_dir,
  File "c:\xinanlin\triton\python\triton\runtime\build.py", line 92, in _build
    subprocess.check_call(cc_cmd, stdout=subprocess.DEVNULL)
  File "C:\Users\sdp\miniforge3\envs\xinanlin\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Intel\\oneAPI\\2025.0\\bin\\icpx.EXE', 'C:\\Users\\sdp\\AppData\\Local\\Temp\\tmpl4ypi1bh\\main.cpp', '-O3', '-shared', '-Wno-psabi', '-lze_loader', '-LC:\\Program Files (x86)\\Intel\\oneAPI\\2025.0\\compiler/latest/lib', '-LC:\\level_zero\\lib', '-LC:\\xinanlin\\triton\\third_party\\intel\\backend\\lib', '-LC:\\Users\\sdp\\miniforge3\\envs\\xinanlin\\Lib\\..\\libs', '-IC:\\level_zero\\include', '-IC:\\Program Files (x86)\\Intel\\oneAPI\\2025.0\\compiler/latest/include', '-IC:\\Program Files (x86)\\Intel\\oneAPI\\2025.0\\compiler/latest/include/sycl', '-IC:\\xinanlin\\triton\\third_party\\intel\\backend\\include', '-IC:\\Users\\sdp\\AppData\\Local\\Temp\\tmpl4ypi1bh', '-IC:\\Users\\sdp\\miniforge3\\envs\\xinanlin\\Include', '-INone', '-IC:\\Users\\sdp\\miniforge3\\envs\\xinanlin\\lib\\site-packages\\numpy\\_core\\include', '-o', 'C:\\Users\\sdp\\AppData\\Local\\Temp\\tmpl4ypi1bh\\spirv_utils.cp39-win_amd64.pyd', '-Wl,-rpath,C:\\Program Files (x86)\\Intel\\oneAPI\\2025.0\\compiler/latest/lib', '-fsycl']' returned non-zero exit status 1181.

```
I've double confirmed that it only happend on the commit you provide, there is no such issue in hot-fix-windows branch.
Is there newer triton commit for me to try the fix?

**Comment by anmyachev** [comment]
> I've double confirmed that it only happend on the commit you provide, there is no such issue in hot-fix-windows branch.
Is there newer triton commit for me to try the fix?

Hi @etaf! Thanks for trying.

There are two options to try. The first is to take the latest commit of the main branch. Windows tests on it should pass now (using icpx). To do this, you need to apply a patch for PyTorch (but you already did this, so it should not be a problem).

The second option is to take https://github.com/intel/intel-xpu-backend-for-triton/tree/hot-fixes-for-pytorch branch and make a cherry pick https://github.com/intel/intel-xpu-backend-for-triton/commit/8bd80f6da4e2c4c313ea2d1f6b69bc108d4762ed commit on it. Looks like last time you just use this commit on the main branch. Sorry I didn't specify that.

**Comment by etaf** [comment]
> > I've double confirmed that it only happend on the commit you provide, there is no such issue in hot-fix-windows branch.
> > Is there newer triton commit for me to try the fix?
> 
> Hi [@etaf](https://github.com/etaf)! Thanks for trying.
> 
> There are two options to try. The first is to take the latest commit of the main branch. Windows tests on it should pass now (using icpx). To do this, you need to apply a patch for PyTorch (but you already did this, so it should not be a problem).
> 
> The second option is to take https://github.com/intel/intel-xpu-backend-for-triton/tree/hot-fixes-for-pytorch branch and make a cherry pick [8bd80f6](https://github.com/intel/intel-xpu-backend-for-triton/commit/8bd80f6da4e2c4c313ea2d1f6b69bc108d4762ed) commit on it. Looks like last time you just use this commit on the main branch. Sorry I didn't specify that.

Hi @anmyachev I've tried option 1, but still get the error:
```
(xinanlin) C:\xinanlin\pytorch>python test\inductor\test_benchmarking.py TestBenchmarker.test_benchmark_gpu_smoke_benchmarker_cls1
WARNING:root:Wall time is used instead of elapsed_time because of the bug ('negative timings').         Should be fixed in DLE 2025.1. The timing measurements could be innacurate.
inductor [('benchmarking.TritonBenchmarker.benchmark_gpu', 1), ('benchmarking.TritonBenchmarker.triton_do_bench', 1)]
F
======================================================================
FAIL: test_benchmark_gpu_smoke_benchmarker_cls1 (__main__.TestBenchmarker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 3114, in wrapper
    method(*args, **kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 557, in instantiated_test
    test(self, **param_kwargs)
  File "c:\xinanlin\pytorch\torch\testing\_internal\common_utils.py", line 840, in test_wrapper
    return test(*args, **kwargs)
  File "C:\xinanlin\pytorch\test\inductor\test_benchmarking.py", line 82, in test_benchmark_gpu_smoke
    self.assertGreater(timing, 0)
AssertionError: 0.0 not greater than 0

To execute this test, run the following from the base repo dir:
    python test\inductor\test_benchmarking.py TestBenchmarker.test_benchmark_gpu_smoke_benchmarker_cls1

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 5.331s

FAILED (failures=1)
```

Triton commit:
commit fa341e9a6941436c5f5ddeece77c9547c86343bc (HEAD, origin/main, origin/HEAD)
Author: Whitney Tsang <whitney.tsang@intel.com>
Date:   Sun Jan 19 21:19:17 2025 +0000

    Fix `test_functional_regressions.py::test_vecmat`

    Signed-off-by: Whitney Tsang <whitney.tsang@intel.com>

**Comment by anmyachev** [comment]
Hi @etaf! 

> AssertionError: 0.0 not greater than 0

I have reproduced this issue. We use the `time.time_ns` function in case the `elapsed_time` function does not work correctly. Its resolution is sufficient for Linux, but not enough for Windows. I prepared a one-line patch https://github.com/intel/intel-xpu-backend-for-triton/pull/3220 that changes the time function to `time.perf_counter_ns` for both system.

**Comment by etaf** [comment]
@anmyachev greate, the case pass now, thanks.

**Comment by anmyachev** [comment]
> [@anmyachev](https://github.com/anmyachev) greate, the case pass now, thanks.

Great!

@etaf now the main question, do you need to port these changes to the branch with fixes for Windows or are you successfully using our PyTorch patch and main branch for now?

**Comment by etaf** [comment]
> > [@anmyachev](https://github.com/anmyachev) greate, the case pass now, thanks.
> 
> Great!
> 
> [@etaf](https://github.com/etaf) now the main question, do you need to port these changes to the branch with fixes for Windows or are you successfully using our PyTorch patch and main branch for now?

I'll move to the main branch, but our E2E CI test still use the `hot-fix-windows` branch because the main branch is not stable. If there is E2E dependency on this issue, I'll ask your help to make a cherry-pick, thanks.
