### ISSUE TITLE
matmul tutorial not working due to oneAPI 2024.0.1

### ISSUE THREAD

**Issue by lmontigny** [intel/intel-xpu-backend-for-triton#324]
Using oneAPI 2024.0.1, the example from the tutorial `python/tutorials/03-matrix-multiplication.py` is not working anymore. (I discussed it with @whitneywhtsang)

oneAPI 2024.1:
```
$ python3 03-matrix-multiplication.py 
Traceback (most recent call last):
  File "/home/jovyan/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 309, in <module>
    triton_output = matmul(a, b)
  File "/home/jovyan/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 289, in matmul
    matmul_kernel[grid](
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 160, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 144, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 144, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 123, in _bench
    return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/testing.py", line 100, in do_bench
    fn()
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 110, in kernel_call
    self.fn.run(
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 406, in run
    kernel.run(grid_0, grid_1, grid_2, metadata.num_warps,
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 321, in __getattribute__
    self._init_handles()
  File "/home/jovyan/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 316, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.utils.load_binary(
RuntimeError: Triton Error [ZE]: 1879048196
```

Using the previous oneAPI 2023.2, it is running correcly.
```
triton_output=tensor([[ -70.1298,  289.5023,    9.0147,  ...,  -64.3087,  -46.5697,
          -60.8229],
        [ 259.5196,   22.6042,  102.2040,  ...,  118.8568,   55.1817,
           63.5758],
        [  17.8615,   57.4507,  120.2733,  ...,  151.5189,  -46.2153,
           50.6026],
        ...,
        [ -78.1537,   -5.2782,  -20.6599,  ...,   53.7101, -113.7878,
           -3.4730],
        [ -49.7085,  -80.2077,  -28.9056,  ...,  182.3028, -226.1966,
          144.4827],
        [ 206.3904, -160.7867,  169.6606,  ...,  -65.7270,  -36.8898,
           -0.8096]], device='xpu:0')
```

**Comment by tdeng5** [comment]
Why do we use oneAPI2024.1 here? we need to base on a stable toolchain and stable Triton version for the coming (Feb 29th) release developing.

**Comment by whitneywhtsang** [comment]
> Both IPEX and Triton project are based on oneAPI2024.0, propose to postpone oneAPI 2024.1 related issues to next iteration.

This issue is reproducible with oneAPI2024.0.

**Comment by quintinwang5** [comment]
Duplicate with https://github.com/intel/intel-xpu-backend-for-triton/issues/338

**Comment by quintinwang5** [comment]
> @quintinwang5 given that #338 is done, can this issue be closed ?

I think so.

**Comment by vlad-penkin** [comment]
Duplicate
