### ISSUE TITLE
Released version is buggy

### ISSUE THREAD

**Issue by chsasank** [intel/intel-xpu-backend-for-triton#334]
I am looking to reproduce data from this tutorial: https://triton-lang.org/main/getting-started/tutorials/03-matrix-multiplication.html and estimate the perf of intel triton generated vs onemkl.

I tried to build but couldn't (I'll create another issue if I can't fix it). So I downloaded the wheel file from releases (dec  19th) and installed it. Then I ran matrix multiplication tutorial in the repo. Here's the error I get when I did that:

```
sasank@ubuntu-22-04:~/code/intel-xpu-backend-for-triton/python/tutorials$ python3 03-matrix-multiplication.py 
/home/sasank/.local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/home/sasank/code/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 309, in <module>
    triton_output = matmul(a, b)
  File "/home/sasank/code/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 289, in matmul
    matmul_kernel[grid](
  File "/home/sasank/.local/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in run
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/sasank/.local/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 100, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs)
  File "/home/sasank/.local/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 83, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/home/sasank/.local/lib/python3.10/site-packages/triton/testing.py", line 105, in do_bench
    torch.cuda.synchronize()
  File "/home/sasank/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 795, in synchronize
    _lazy_init()
  File "/home/sasank/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

It looks like there's still some cuda code left in the release. I have checked the code in the repo and it looks like the relevant line is already replaced. 

Here are my two requests:
1. Please update the releases with latest builds
2. Publish benchmarks for matmul and others to instill confidence in the repo

Looking forward to contribute more to the repo.

**Comment by etiotto** [comment]
Yes, the port is WIP. Not all benchmark can be compiled end-to-end.

**Comment by whitneywhtsang** [comment]
Yes, 03-matrix-multiplication doesn't currently work, tracked by https://github.com/intel/intel-xpu-backend-for-triton/issues/324.
But the error you are facing looks different, can you try to use the scripts to compile and test? The scripts installs requires packages like https://github.com/intel/intel-xpu-backend-for-triton/blob/llvm-target/scripts/test-triton.sh#L59.
```
scripts/compile-triton.sh
scripts/test-triton.sh --tutorial
```
Note: 03-matrix-multiplication is not part of `scripts/test-triton.sh`, but you can add it there locally.

**Comment by whitneywhtsang** [comment]
Which released version are you referring to?

**Comment by chsasank** [comment]
@whitneywhtsang: I am referring to this release here: https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/v2.1.0

**Comment by whitneywhtsang** [comment]
> @whitneywhtsang: I am referring to this release here: https://github.com/intel/intel-xpu-backend-for-triton/releases/tag/v2.1.0

As mentioned by Ettore in https://github.com/intel/intel-xpu-backend-for-triton/issues/327#issuecomment-1904645404, we have 2 different implementations: one that translates Triton operators to the SPIR MLIR dialect and one that translate them to the LLVM MLIR dialect. The release you are referring to is the first implementation that translates Triton operators to SPIR MLIR dialect. @chengjunlu Do you know if 03-matrix-multiplication works with v2.1.0 release?

**Comment by chengjunlu** [comment]
v2.1.0 doesn't support all data type for the matmul.
It only supports FP32 data type by lowering it to the FMA op.

Unfortunately, the 03-matrix-multiplication uses the fp16 then it couldn't run on XPU by default.

**Comment by whitneywhtsang** [comment]
@chsasank Any other questions for this issue?

**Comment by chsasank** [comment]
Would like to see some benchmarks vs onemkl 😅. Even if it's for fp32.

Also please setup CI/CD to release wheels on github more often.

**Comment by whitneywhtsang** [comment]
> Also please setup CI/CD to release wheels on github more often.

@pbchekin could you please comment on this.

**Comment by pbchekin** [comment]
> Would like to see some benchmarks vs onemkl 😅. Even if it's for fp32.
> 
> Also please setup CI/CD to release wheels on github more often.

We will shortly, but before that we need to increase our functional completeness.

**Comment by anmyachev** [comment]
@pbchekin should we close this issue?

**Comment by pbchekin** [comment]
Closing this issue. Will open a new one if there are any issues with the nightly wheels.
