### ISSUE TITLE
Runtime Error for Tutorial tests 03, 08, 09 and 10

### ISSUE THREAD

**Issue by prathams417** [intel/intel-xpu-backend-for-triton#338]
```
self.module, self.function, self.n_regs, self.n_spills = driver.utils.load_binary(
RuntimeError: Triton Error [ZE]: 2013265937
```

To reproduce issue:

```
python3 -m pip install matplotlib pandas tabulate -q
python3 python/tutorials/<test-name>
```

Could be resolved by #324

**Comment by tdeng5** [comment]
Will this issue impact the coming release for IPEX in the end of Feb? if no, prefer to lower the priority.

**Comment by whitneywhtsang** [comment]
This issue is likely a duplication of https://github.com/intel/intel-xpu-backend-for-triton/issues/324, as all 4 tutorials fail with `error: total scratch space exceeds HW supported limit`.

**Comment by chsasank** [comment]
Can reproduce the error with freshly built triton (see #335). 

```
(triton) sasank@ubuntu-22-04:~/code/triton-build/intel-xpu-backend-for-triton/python/tutorials$ python 03-matrix-multiplication.py 
/home/sasank/code/triton-build/intel-xpu-backend-for-triton/.venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 309, in <module>
    triton_output = matmul(a, b)
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/tutorials/03-matrix-multiplication.py", line 289, in matmul
    matmul_kernel[grid](
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 160, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 144, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 144, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 123, in _bench
    return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/testing.py", line 100, in do_bench
    fn()
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/runtime/autotuner.py", line 110, in kernel_call
    self.fn.run(
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 406, in run
    kernel.run(grid_0, grid_1, grid_2, metadata.num_warps,
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 321, in __getattribute__
    self._init_handles()
  File "/home/sasank/code/triton-build/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 316, in _init_handles
    self.module, self.function, self.n_regs, self.n_spills = driver.utils.load_binary(
RuntimeError: Triton Error [ZE]: 1879048196
```

Details about my environment, see https://github.com/intel/intel-extension-for-pytorch/issues/513. 

```
Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
Is XPU available: True
DPCPP runtime version: 2024.0
MKL version: 2024.0
```

**Comment by etiotto** [comment]
I have a temp. fix for  the `03-matrix-multiplication.py` in PR #359.

**Comment by ESI-SYD** [comment]
#### 06 08 09 10 fails in spirv-target for reference
output like:
```
loc("-":54:11): error: Dialect `triton_nvidia_gpu' not found for custom op 'triton_nvidia_gpu.alloc_mbarrier' 
Traceback (most recent call last):
  File "/workspace/tutorials/10-experimental-tma-store-matrix-multiplication.py", line 110, in <module>
    c = matmul(a, b)
  File "/workspace/tutorials/10-experimental-tma-store-matrix-multiplication.py", line 99, in matmul
    matmul_kernel[grid](
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 156, in run
    ret = self.fn.run(
  File "/opt/conda/lib/python3.10/site-packages/triton/runtime/jit.py", line 532, in run
    self.cache[device][key] = compile(
  File "/opt/conda/lib/python3.10/site-packages/triton/compiler/compiler.py", line 543, in compile
    next_module = compile_kernel(module)
  File "/opt/conda/lib/python3.10/site-packages/triton/third_party/xpu/__init__.py", line 456, in <lambda>
    lambda src: ttgir_to_spirv(src, extern_libs, arch))
  File "/opt/conda/lib/python3.10/site-packages/triton/third_party/xpu/__init__.py", line 102, in ttgir_to_spirv
    spirv_code, share_memory_size = _triton.translate_triton_gpu_to_spirv(str(mod), arch)  # noqa: E501
RuntimeError: Parse MLIR file failed.
```
