### ISSUE TITLE
An correctness issue happened when run the Triton tutorial example 10 with the threads_per_warp=16.

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#436]
When lowering the GEMM kernel to the FMA ops with the threads_per_warp=16, the Triton tutorial example 10 reports the correctness issue.

It seems a correctness issue because the relative difference exceeds the expectation too much.

Here is the log of the failed case:
```
Traceback (most recent call last):
  File "/runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/python/tutorials/10-experimental-tma-store-matrix-multiplication.py", line 119, in <module>
    assert_close(c, golden, rtol=1e-2, atol=1e-3, check_dtype=False)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1520, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 257384 / 262144 (98.2%)
Greatest absolute difference: 0.7141353487968445 at index (192, 259) (up to 0.001 allowed)
Greatest relative difference: 3702.51318359375 at index ([440](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/7737679640/job/21097071205?pr=414#step:17:441), 131) (up to 0.01 allowed
```

**Comment by etiotto** [comment]
The tutorial is currently clean. This work item is not directly related to the tutorial pass rate. It is related to the performance feature for `tl.dot` operation (DPAS enablement)
