### ISSUE TITLE
[timm][training][amp_fp32] `mobilenetv2_100` and `rexnet_100` failed to load

### ISSUE THREAD

**Issue by whitneywhtsang** [intel/intel-xpu-backend-for-triton#521]
```
Test amp with dt: torch.float16

loading model: 0it [00:00, ?it/s]
loading model: 0it [00:08, ?it/s]
WARNING:root:rexnet_100 failed to load
Eager model failed to run
Traceback (most recent call last):
  File "/home/jovyan/pytorch/benchmarks/dynamo/common.py", line 1869, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/home/jovyan/pytorch/benchmarks/dynamo/timm_models.py", line 332, in forward_and_backward_pass
    self.grad_scaler.scale(loss).backward()
  File "/home/jovyan/.conda/envs/timm/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/jovyan/.conda/envs/timm/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: "hardtanh_backward" not implemented for 'Half'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jovyan/pytorch/benchmarks/dynamo/common.py", line 3451, in run
    ) = runner.load_model(
  File "/home/jovyan/pytorch/benchmarks/dynamo/timm_models.py", line 268, in load_model
    self.validate_model(model, example_inputs)
  File "/home/jovyan/pytorch/benchmarks/dynamo/common.py", line 1871, in validate_model
    raise NotImplementedError("Eager model failed to run") from e
NotImplementedError: Eager model failed to run
```

**Comment by whitneywhtsang** [comment]
Not regression, lowered priority.

**Comment by Stonepia** [comment]
This should be fixed in https://github.com/intel/intel-extension-for-pytorch/commit/f496a32aed6d9ad4c70fcbbf2d3321a385affccb

**Comment by vlad-penkin** [comment]
Issue is no longer reproducible.

 Env:
- pytorch is built from source, top of the main trunk, commit_id - `9a8ab778d34bd24c5caceb340837483decc4c311`
- triton xpu is built from source, top of the main trunk, commit_id - `fe93a00ffe438e9ba8c8392c0b051b1662c810de`
- benchmark is built from source, top of the main trunk, commit_id - `d54ca9f80ead108c8797441681e219becaf963d8`
- torchaudio is built from source, top of the main trunk,  commit_id - `1980f8af5bcd0bb2ce51965cf79d8d4c25dad8a0`
- torchvision  is built from source, top of the main trunk,  commit_id - `10239873229e527f8b7e7b3340c40ee38bb1cfc4`
- PyTorch Dependency Bundle 0.5.0
- Latest Rolling Driver
