### ISSUE TITLE
Circular dependency in PyTorch/IPEX/Triton

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#582]
Steps to reproduce:
* Install PyTorch from sources (Stonepia/pytorch, branch dev/triton-test-3.0)
* Install IPEX from sources (intel/intel-extension-for-pytorch, branch dev/triton-test-3.0)
* Execute `python -c "import torch;import intel_extension_for_pytorch as ipex;print(ipex.__version__)"`

Result:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 122, in <module>
    from . import _dynamo
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/_dynamo/__init__.py", line 6, in <module>
    from torch._inductor import codecache  # noqa
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_inductor/codecache.py", line 43, in <module>
    from torch._inductor.utils import developer_warning
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/torch/_inductor/utils.py", line 487, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
```

Potential root cause: https://github.com/Stonepia/pytorch/commit/cbd2bb7011a63102e3f9235b03e0ce300d151e51

**Comment by Stonepia** [comment]
Hello, I have reverted the commit. https://github.com/Stonepia/pytorch/commit/c373c5baf9ac722bf653b30767638503c9a3e97d
