### ISSUE TITLE
[torchbench] moco model fails because it tries to initialize distributed processing with NCCL backend

### ISSUE THREAD

**Issue by gshimansky** [intel/intel-xpu-backend-for-triton#595]
Symptom: moco fails with exception in DistributedDataParallel:
```
Traceback (most recent call last):
  File "/home/jovyan/work/triton-no-conda/pytorch/benchmarks/dynamo/torchbench.py", line 481, in <module>
    torchbench_main()
  File "/home/jovyan/work/triton-no-conda/pytorch/benchmarks/dynamo/torchbench.py", line 477, in torchbench_main
    main(TorchBenchmarkRunner(), original_dir)
  File "/home/jovyan/work/triton-no-conda/pytorch/benchmarks/dynamo/common.py", line 3045, in main
    process_entry(0, runner, original_dir, args)
  File "/home/jovyan/work/triton-no-conda/pytorch/benchmarks/dynamo/common.py", line 3002, in process_entry
    return maybe_fresh_cache(
  File "/home/jovyan/work/triton-no-conda/pytorch/benchmarks/dynamo/common.py", line 1665, in inner
    return fn(*args, **kwargs)
  File "/home/jovyan/work/triton-no-conda/pytorch/benchmarks/dynamo/common.py", line 3455, in run
    ) = runner.load_model(
  File "/home/jovyan/work/triton-no-conda/pytorch/benchmarks/dynamo/torchbench.py", line 366, in load_model
    benchmark = benchmark_cls(
  File "/home/jovyan/work/triton-no-conda/benchmark/torchbenchmark/util/model.py", line 24, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/jovyan/work/triton-no-conda/benchmark/torchbenchmark/models/moco/__init__.py", line 85, in __init__
    self.model = torch.nn.parallel.DistributedDataParallel(
  File "/home/jovyan/.conda/envs/triton-no-conda-3.10-stonepia/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 734, in __init__
    self.process_group = _get_default_group()
  File "/home/jovyan/.conda/envs/triton-no-conda-3.10-stonepia/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 940, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

The problem actually is that moco calls `init_process_group` but ignores an exception risen by it:
```
  File "/home/jovyan/work/triton-no-conda/benchmark/torchbenchmark/models/moco/__init__.py", line 60, in __init__
    dist.init_process_group(
  File "/home/jovyan/.conda/envs/triton-no-conda-3.10-stonepia/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/jovyan/.conda/envs/triton-no-conda-3.10-stonepia/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/jovyan/.conda/envs/triton-no-conda-3.10-stonepia/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1268, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL built in")
RuntimeError: Distributed package doesn't have NCCL built in
```

We currently have pytorch that is built without NCCL support.

**Comment by gshimansky** [comment]
Looks like pytorch cannot be built with NCCL support when there is no CUDA:
```
CMake Warning at cmake/Dependencies.cmake:1340 (message):
  Not using CUDA/ROCM, so disabling USE_NCCL.  Suppress this warning with
  -DUSE_NCCL=OFF.
```

**Comment by gshimansky** [comment]
[moco.patch](https://github.com/intel/intel-xpu-backend-for-triton/files/14465459/moco.patch)
Attached is a patch that seems to allow to run this model on PVC with triton. The problem is that if I comment the `print` statement in `concat_all_gather` I am getting an exception. When `print` is not commented the model works normally although it fails accuracy test.

**Comment by vlad-penkin** [comment]
No updates in year. Closing ticket.
