### ISSUE TITLE
E2E torchbench regression

### ISSUE THREAD

**Issue by pbchekin** [intel/intel-xpu-backend-for-triton#694]
Torchbench e2e tests fail with the following error:

```
ImportError: /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-gpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev
```

# Steps to reproduce

1. Build and install torch, ipex, torchvision, torchtext, torchaudio from sources (see "Environment" for the details").

2. Verify that both torch and ipex can be imported.

   ```
   python -c "import torch;print(torch.__version__)" 
   python -c "import torch;import intel_extension_for_pytorch as ipex;print(ipex.__version__)"
   ```

3. Clone  weishi-deng/benchmark.git @ main, run

   ```
   python install.py
   pip install -e .
   ```

4. Execute

   ```
   inductor_xpu_test.sh torchbench amp_bf16 inference accuracy xpu 0
   ```

Stack trace:

```
File "/cache/pytorch-3.10-2c5c507e3df4a117e88d3cb29ffb9a87a599dc42-3/benchmarks/dynamo/torchbench.py", line 481, in <module>
    torchbench_main()
  File "/cache/pytorch-3.10-2c5c507e3df4a117e88d3cb29ffb9a87a599dc42-3/benchmarks/dynamo/torchbench.py", line [47](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8308622188/job/22739067150#step:37:48)7, in torchbench_main
    main(TorchBenchmarkRunner(), original_dir)
  File "/cache/pytorch-3.10-2c5c[50](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8308622188/job/22739067150#step:37:51)7e3df4a117e88d3cb29ffb9a87a[59](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8308622188/job/22739067150#step:37:60)9dc42-3/benchmarks/dynamo/common.py", line 3040, in main
    process_entry(0, runner, original_dir, args)
  File "/cache/pytorch-3.10-2c5c507e3df4a117e88d3cb29ffb9a87a599dc42-3/benchmarks/dynamo/common.py", line 2997, in process_entry
    return maybe_fresh_cache(
  File "/cache/pytorch-3.10-2c5c507e3df4a117e88d3cb29ffb9a87a599dc42-3/benchmarks/dynamo/common.py", line 16[60](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8308622188/job/22739067150#step:37:61), in inner
    return fn(*args, **kwargs)
  File "/cache/pytorch-3.10-2c5c507e3df4a117e88d3cb29ffb9a87a599dc42-3/benchmarks/dynamo/common.py", line 3108, in run
    import intel_extension_for_pytorch as ipex
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-gpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev
```

Workflow run (worked before):
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/8308622188/job/22739067150

# Environment

```
PYTHON_VERSION=3.10
PYTORCH_REPO=Stonepia/pytorch
PYTORCH_COMMIT_ID=2c5c507e3df4a117e88d3cb29ffb9a87a599dc42
IPEX_REPO=intel/intel-extension-for-pytorch
IPEX_COMMIT_ID=4df9e1feeedcc312402b20f6c7fa4637be16bea2
LLVM_REPO=intel/llvm.git
LLVM_COMMIT_ID=e65cd965a8f661e2e4af4407876d96b0e2458a76
BENCHMARK_REPO=weishi-deng/benchmark.git
BENCHMARK_COMMIT_ID=1eb816925dc2bf9b5b2ec4537b353c1e4ddcfc35
TRITON_REPO=intel/intel-xpu-backend-for-triton
TRITON_COMMIT_ID=76626004e6f195e1e29d2692496346cda8f295b0
TORCHVISION_COMMIT_ID=47cd5ea8e21d7596a24907710411d6b4a43f628d
TORCHTEXT_COMMIT_ID=b0ebddc648d279826089db91775375221777a2db
TORCHAUDIO_COMMIT_ID=a8f4e97bd5356a7a77510cdf6a3a62e25a5dc602
TRANSFORMERS_VERSION=4.27.4
TIMM_COMMIT_ID=b9d43c7dcac1fe05e851dd7be7187b108af593d2
```

**Comment by pbchekin** [comment]
Simple reproduction:

After installing torchbench with

```
cd benchmark
python install.py
pip install -e .
```

Importing ipex no longer works (worked before installing `benchmark`):

```
$ python -c "import torch;import intel_extension_for_pytorch as ipex;print(ipex.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 94, in <module>
    from .utils._proxy_module import *
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-gpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev
```

**Comment by pbchekin** [comment]
The root cause for the issue is the recent changes to https://github.com/weishi-deng/benchmark. The install/setup code for `benchmark` re-install torch:

* Before installing benchmark: `torch 2.1.0a0+git2c5c507`
* After installing benchmark: `torch 2.2.1`

Also `benchmark` re-installs pinned `transformers`:

* Before installing benchmark: `transformers 4.27.4`
* After installing benchmark: `transformers 4.38.1`

**Comment by weishi-deng** [comment]
Hi, this issue is root caused by the sync of Pytorch/benchmark which includes a new model 'sam_fast' that requires  'torch>=2.2.0'. This workaround is added to our branch to avoid reinstalling the torch while installing the torchbench. As a side effect, this new model will be supported later when IPEX satisfies the requirements.

**Comment by vlad-penkin** [comment]
@pbchekin could please confirm that the issue is resolved

**Comment by pbchekin** [comment]
It is resolved, thanks.
