### ISSUE TITLE
[PyTorch Upstream] atomic_add lowering error

### ISSUE THREAD

**Issue by Stonepia** [intel/intel-xpu-backend-for-triton#699]
Hi,
Due to the changes in https://github.com/intel/intel-xpu-backend-for-triton/issues/589, the atomic_add lowering would raise an error.  We encountered this error with both the latest stock pytorch (in the upstreaming process) and `dev/triton-test-3.0` branch.

## Error Msg
In the following context, the `if not input.type.is_block()` raises error. Because the `input` is `constexpr[None]` rather than `None`.

```Python
Traceback (most recent call last):
  File "/home/user/user/intel-xpu-backend-for-triton/python/triton/language/core.py", line 34, in wrapper
    return fn(*args, **kwargs)
  File "/home/user/user/intel-xpu-backend-for-triton/python/triton/language/core.py", line 1627, in atomic_add
    return semantic.atomic_add(pointer, val, mask, sem, scope, _builder)
  File "/home/user/user/intel-xpu-backend-for-triton/python/triton/language/semantic.py", line 1246, in atomic_add
    ptr, val, mask = atom_red_typechecking_impl(ptr, val, mask, 'add', builder)
  File "/home/user/user/intel-xpu-backend-for-triton/python/triton/language/semantic.py", line 1159, in atom_red_typechecking_impl
    mask = broadcast_impl_shape(mask, ptr.type.get_block_shapes(), builder)
  File "/home/user/user/intel-xpu-backend-for-triton/python/triton/language/semantic.py", line 636, in broadcast_impl_shape
    if not input.type.is_block():
AttributeError: 'constexpr' object has no attribute 'type'

  File "/home/user/user/pytorch/torch/_inductor/triton_heuristics.py", line 179, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/user/user/ipex/intel_extension_for_pytorch/_inductor/xpu/triton_heuristics.py", line 147, in _precompile_config
    triton.compile(*compile_args, **compile_kwargs),
  File "/home/user/user/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 264, in compile
    module = src.make_ir(options, context)
  File "/home/user/user/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 108, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options)
triton.compiler.errors.CompilationError: at 22:4:
    tmp10 = tmp8 + tmp9
    tmp11 = 0.0
    tmp12 = tl.where(tmp3, tmp11, tmp10)
    tl.atomic_add(out_ptr0 + (x0 + (128*tmp1)), tmp12, None)
    ^
```

## Reproducer
```Bash
bash inductor_xpu_test.sh huggingface amp_bf16  training  performance  xpu 1 static 1 0 AlbertForMaskedLM;
```
Or with the following script
```Python
import torch
import intel_extension_for_pytorch
from torch import tensor, device
import torch.fx as fx
from torch._dynamo.testing import rand_strided
from math import inf
from torch.fx.experimental.proxy_tensor import make_fx

import torch._dynamo.config
import torch._inductor.config
import torch._functorch.config

from torch.nn import *
class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.full_4 = rand_strided((32, 8), (8, 1), device='xpu:0', dtype=torch.float32)
        self.add_37 = rand_strided((1024, 1024), (1024, 1), device='xpu:0', dtype=torch.int64)
        self.clone_129 = rand_strided((1024, 1024, 8), (8192, 8, 1), device='xpu:0', dtype=torch.float32)
    def forward(self):
        index_put = torch.ops.aten.index_put.default(self.full_4, [self.add_37], self.clone_129, True)
        return [index_put]

args=[]
mod = torch.compile(Repro())
ref = mod(*args)
```

**Comment by etaf** [comment]
@riverliuintel @vlad-penkin :
This bug was also found in pytorch upstream. We got the same error in Inductor UT。
You can also reproduece in IPEX by runing the follow case:
python tests/gpu/pytorch/test/inductor/test_torchinductor.py -k test_index_put2_xpu

And this seems to be a regression:
latest triton with commit : 0b0b8d785f1c30e8ffa1edafc243f956fe6f19d8  fail
but the old commit: 95891675e51a71440d345d7bf8d054cb62e9ded5  passed.

**Comment by riverliuintel** [comment]
@whitneywhtsang  please notes this PR will break Triton CI in latest test proxy, if not update Triton code. The stable version that we give last Friday for test proxy is no problem to co-work with current Triton.

**Comment by whitneywhtsang** [comment]
@etaf Please verify.

**Comment by vlad-penkin** [comment]
@etaf please confirm

**Comment by Stonepia** [comment]
Checked with AlbertForMaskedLM and could pass. thanks for the help~!

**Comment by etaf** [comment]
verifyied in Inductor UT, thanks @whitneywhtsang  @vlad-penkin .
