### ISSUE TITLE
[Torch Inductor] Regression with the latest Triton 3.0. None value is wrapped by the tl.core.constexpr value

### ISSUE THREAD

**Issue by chengjunlu** [intel/intel-xpu-backend-for-triton#735]
There is a regression issue in torch inductor backend with the latest Triton 3.0.

```
Console output is saving to: /home/chengjun/workspace/CLionProject/triton-xpu-fork/unit_test.log
Traceback (most recent call last):
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/python/triton/language/core.py", line 34, in wrapper
    return fn(*args, **kwargs)
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/python/triton/language/core.py", line 1650, in atomic_add
    return semantic.atomic_add(pointer, val, mask, sem, scope, _builder)
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/python/triton/language/semantic.py", line 1252, in atomic_add
    ptr, val, mask = atom_red_typechecking_impl(ptr, val, mask, 'add', builder)
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/python/triton/language/semantic.py", line 1165, in atom_red_typechecking_impl
    mask = broadcast_impl_shape(mask, ptr.type.get_block_shapes(), builder)
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/python/triton/language/semantic.py", line 641, in broadcast_impl_shape
    if not input.type.is_block():
AttributeError: 'constexpr' object has no attribute 'type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/test.py", line 1393, in <module>
    triton_red_fused_embedding_dense_backward_sum_27 = async_compile.triton('triton_red_fused_embedding_dense_backward_sum_27', '''
  File "/home/chengjun/workspace/CLionProject/ipex/intel_extension_for_pytorch/_inductor/xpu/codecache.py", line 82, in triton
    return _load_kernel(kernel_name, source_code)
  File "/home/chengjun/workspace/CLionProject/pytorch/torch/_inductor/codecache.py", line 1274, in _load_kernel
    kernel.precompile()
  File "/home/chengjun/workspace/CLionProject/pytorch/torch/_inductor/triton_heuristics.py", line 178, in precompile
    self.launchers = [
  File "/home/chengjun/workspace/CLionProject/pytorch/torch/_inductor/triton_heuristics.py", line 179, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/chengjun/workspace/CLionProject/ipex/intel_extension_for_pytorch/_inductor/xpu/triton_heuristics.py", line 155, in _precompile_config
    binary = triton.compile(*compile_args, **compile_kwargs)
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/python/triton/compiler/compiler.py", line 266, in compile
    module = src.make_ir(options, context)
  File "/home/chengjun/workspace/CLionProject/triton-xpu-fork/python/triton/compiler/compiler.py", line 110, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options)
triton.compiler.errors.CompilationError: at 28:4:
        _tmp2 = tl.where(rmask, tmp3, _tmp2)
    tmp2 = tl.sum(_tmp2, 1)[:, None]
    x3 = (xindex // 768)
    x2 = xindex % 768
    tmp4 = tl.load(in_ptr1 + (x3), None, eviction_policy='evict_last')
    tmp5 = tl.where(tmp4 < 0, tmp4 + 512, tmp4)
    tmp6 = tl.full([1, 1], -1, tl.int64)
    tmp7 = tmp4 == tmp6
    tmp8 = tmp2.to(tl.float32)
    tmp9 = 0.0
    tmp10 = tl.where(tmp7, tmp9, tmp8)
    tl.atomic_add(out_ptr1 + (x2 + (768*tmp5)), tmp10, None)
    ^
```

**Comment by whitneywhtsang** [comment]
Duplication of https://github.com/intel/intel-xpu-backend-for-triton/issues/699.

**Comment by chengjunlu** [comment]
Close this issue as duplicated.
