### ISSUE TITLE
tanh function is missing from triton

### ISSUE THREAD

**Issue by Egor-Krivov** [intel/intel-xpu-backend-for-triton#881]
I cannot find tanh function in xpu-triton. tanh is used quite often in DL, for example, in geglu: https://github.com/unslothai/unsloth/blob/d215fd902cf28feb8abcfde2d25281d0fbf9d28c/unsloth/kernels/geglu.py#L122

It should be here: `triton.language.math.tanh`. CUDA-based triton supports tanh function.

Code:
```import torch
import intel_extension_for_pytorch  # type: ignore # noqa: F401

import triton
import triton.language as tl


@triton.jit
def add_kernel(x_ptr,  # *Pointer* to first input vector.
               y_ptr,  # *Pointer* to second input vector.
               output_ptr,  # *Pointer* to output vector.
               n_elements,  # Size of the vector.
               BLOCK_SIZE: tl.constexpr,  # Number of elements each program should process.
               # NOTE: `constexpr` so it can be used as a shape value.
               ):
    pid = tl.program_id(axis=0)  # We use a 1D launch grid so axis is 0.
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask)
    y = tl.load(y_ptr + offsets, mask=mask)
    output = x * tl.math.tanh(y)
    tl.store(output_ptr + offsets, output, mask=mask)


def add(x: torch.Tensor, y: torch.Tensor):
    output = torch.empty_like(x)
    assert x.is_xpu and y.is_xpu and output.is_xpu
    n_elements = output.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta['BLOCK_SIZE']), )
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
    return output


torch.manual_seed(0)
size = 1024 
x = torch.rand(size, device='xpu')
y = torch.rand(size, device='xpu')
output_torch = x * torch.tanh(y)
output_triton = add(x, y)
print(output_torch)
print(output_triton)
print(f'The maximum difference between torch and triton is '
      f'{torch.max(torch.abs(output_torch - output_triton))}')
```

Traceback:
```Traceback (most recent call last):
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/tutorials/tanh_test.py", line 40, in <module>
    output_triton = add(x, y)
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/tutorials/tanh_test.py", line 31, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 207, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 441, in run
    self.cache[device][key] = compile(
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 233, in compile
    key = f"{triton_key()}-{src.hash()}-{backend.hash()}-{options.hash()}-{str(sorted(get_env_vars().items()))}"
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/compiler/compiler.py", line 108, in hash
    key = f"{self.fn.cache_key}-{self.attrs.hash()}-{sorted_sig}-{sorted_constants}"
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 514, in cache_key
    dependencies_finder.visit(self.parse())
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 86, in visit_FunctionDef
    self.generic_visit(node)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 415, in generic_visit
    self.visit(item)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 96, in visit_Assign
    self.generic_visit(node)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 417, in generic_visit
    self.visit(value)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 417, in generic_visit
    self.visit(value)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 60, in visit_Call
    func = self.visit(node.func)
  File "/home/jovyan/.conda/envs/python-3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/home/jovyan/triton/intel-xpu-backend-for-triton/python/triton/runtime/jit.py", line 50, in visit_Attribute
    return getattr(lhs, node.attr)
AttributeError: module 'triton.language.math' has no attribute 'tanh'
```

**Comment by ienkovich** [comment]
tanh is now a part of libdevice. You get it as `from triton.language.extra.intel import libdevice`
